import LocalizedStrings from 'localized-strings';

// First language is used as the default when browser language is different from provided languages

const localization = new LocalizedStrings({
	en: {
		about: [
			'SIGame is an intellectual quiz in which everyone can test their knowledge and reaction speed and fight against opponents.',
			`Game rules are very simple: all questions in the game are divided into themes,
			 and each question in the theme has its own price.
			 Each player has a personal score, which at the beginning of the game is 0.
			 A question is presented, after which a frame appears on the screen indicating that you can press the button and answer.
			 If the player knows the answer, he/she can press the red button. The player who presses the button earlier than others
			 (and will not have a false start), gives an answer. If the answer is correct, the question price is added to the player's score;
			 otherwise - the price is substracted from the score.
			 In the latter case, other players can try their luck and press the button to answer.`,
			`There are also special questions in the game.
			In the "Stake Question" the participants bid for a question, and the player with the highest bet answers.
			In this case, the "All-in" bet (the bet which is equal to the whole player score) can only be outbid by another "All-in".`,
			`"Secret Question" must be given to another player.
			The player who received it must (if it is included in the question) choose the price of the question and answer it.
			The theme of the question may differ from the main theme in which the question was opened.`,
			'"Question for yourself" is answered by the player who opened it.',
			`The game can also have a final round in which each of the players makes a stake.
			A question is asked, time is given for thinking, and each of the players submits their answer to the host.
			After that, the correct answer is announced, and each of the players receives or loses money according to their bet.`,
			'The game winner is the player with the highest score after the last question.',
			'The game button can also be activated using the specified key or the right mouse button.'
		],
		aboutAuthor: 'Author',
		aboutSupport: 'Technical support',
		aboutTitle: 'About',
		acceptLicense: 'Accept license',
		addedNewSlot: '{0} added new player slot',
		addOption: 'Add option',
		addContentItem: 'Add content item',
		addScreen: 'Add screen',
		addTable: 'Add table',
		all: 'All',
		allIn: 'ALL IN!',
		allowEveryoneToPlayHiddenStakes: 'Every player playes',
		allowEveryoneToPlayHiddenStakesHint: 'even having 0 or negative score',
		answer: 'Answer',
		answerChecking: 'Answer check',
		answerOptions: 'Answer options',
		answerType: 'Answer type',
		answerTypeSelect: 'Select from options',
		anyonePlay: 'Play with random opponents',
		apellateAnswer: 'Appellate answer',
		apellation: 'Appellation',
		appellationMark: 'Appellation requested',
		apiCallsQuotaExceeded: 'Requests quota exceeded. Please try again later',
		appName: 'SIGame',
		appUser: 'SIGame',
		ascending: 'ascending',
		attachContentToTable: 'Add theme comments and right answers to game table',
		audio: 'Audio',
		audioLoadError: 'Audio loading error',
		authorInfo: 'Vladimir Khil',
		authors: 'Authors',
		avatar: 'Avatar',
		avatarLoadError: 'Avatar upload error',
		backgroundColor: 'Background color',
		backgroundImage: 'Background image',
		badPackage: 'Bad question package!',
		ban: 'Ban',
		bannedNotification: '{0} kicked {1} from the game',
		bannedList: 'Banned list',
		blocked: '(Blocked)',
		bot: 'Bot',
		buttonPressMode: 'Button press mode',
		buttonPressModeFirstWins: 'Who pressed first (according to server)',
		buttonPressModeFirstWinsClient: 'Who pressed first (according to client)',
		buttonPressModeRandomWithinInterval: 'Random from early pressers',
		by: 'by',
		byGame: 'by game',
		cancelAnswer: 'Cancel player answering',
		cannotConnectToServer: 'Cannot connect to server',
		cancel: 'Cancel',
		changedSlotType: '{0} changed {1}\'s player slot type to: {2}',
		changeSums: 'Change sums',
		changeToBot: 'Change to bot',
		changeToHuman: 'Change to human',
		chat: 'Chat',
		chooserMark: 'Question chooser mark',
		close: 'Close',
		comment: 'Comment',
		comments: 'Comments',
		common: 'Common',
		complain: 'Complain',
		complainHint: 'The question contains spelling or factual error',
		composer: 'Composer',
		computer: 'Bot',
		computerAccountsMissing: 'Computer accounts not loaded. Try to reload the game',
		computerPlayers: 'Bots',
		connected: '{0} connected',
		connectionClosed: 'Server connection lost!',
		connectionReconnecting: 'Connection lost, trying to reconnect…',
		connectionReconnected: 'Connection restored!',
		contactUri: 'Authors contact',
		content: 'Content',
		cookiesConfirm: 'Accept cookies',
		cookiesWarning: 'This application uses cookies. If you stay on this page, you ageee with that',
		copyrightIssue: 'Copyright issue',
		copyText: 'Copy text to clipboard',
		corruptedPackage: 'Question package is corrupted!',
		created: 'Created',
		createOwnPackage: 'Create your own package',
		createPackage: 'Create package',
		creatingGame: 'Creating game…',
		date: 'Date',
		default: 'Common',
		defaultFont: '(default)',
		defaultShowman: 'Leonardo da Vinci',
		delete: 'Delete',
		deleteAvatar: 'Delete avatar',
		deletedSlot: '{0} deleted player slot {1}',
		deleteTable: 'Delete table',
		demoAbout: `SIGame is an intellectual quiz game where you can test your knowledge and reaction speed against opponents.
	Speed and knowledge are keys to victory.
	Question is presented, after which a frame appears on the screen indicating that you can press the button and answer.
	Let's check how it works: there will be a question on the screen, and you need to press the button as quickly as possible`,
		demoCorrectAnswer: 'You have given the correct answer! Your score is increased by question price',
		demoFalseStarts: `If the game is played without false starts, the frame (and the ability to press the button)
	will appear immediately with the question`,
		demoFinished: 'Demo finished. Thank you!',
		demoGameRules: 'By answering questions, you can earn points. A player having the most points at the end of the game wins',
		demoGiveAnswer: 'Now print answer to the question. Print: ANSWER and press Send button or Enter',
		demoOpponents: `You can play with bots or with your friends.
		You can use built-in questions, take questions made by other authors or create your own`,
		demoOtherContent: `There could be images, audio and video in a question.
	There could also be multiple choice questions where you can select right answer from the list`,
		demoOtherQuestions: `There could be other types of questions in the game: for example, Question with stake or Question with secret.
	There would be explanations of these questions rules during the game`,
		demoQuestion: `This is a demo question. Press the button to answer.
		If you press the button before the frame appears, it will be a false start and your button will not work for some time.
		If you press the button but another player beats you, your button will also be blocked.
		The first player who presses the button will answer the question`,
		demoWelcome: `Welcome to SIGame!
	You can always exit demo mode by clicking "Exit" button in the corner of the screen.
	To start demonstration click "Ready" button (green checkmark)`,
		demoWrongAnswer: 'You have given wrong answer! Your score is decreased by the question price',
		descending: 'descending',
		disconnected: '{0} disconnected',
		difficulty: 'Difficulty',
		disableSound: 'Disable sound',
		siStorageDisclaimer: `Attention! This section contains materials of third-party authors.
	Authors of packages in the library are responsible for the content of the packages, their accuracy and compliance with the law`,
		displayAnswerOptionsLabels: 'Display answer options labels',
		displayAnswerOptionsOneByOne: 'Display answer options one by one',
		displaySources: 'Display questions sources',
		donate: 'Donate',
		donateComment: `Donations are optional and are used exclusively to cover hosting and domain expenses.
The project is non-commercial and exists for educational purposes.
All game functionality is available for free—donations do not affect gameplay or grant access to additional features. Thank you for your support!`,
		donateServersHosting: 'DONATE: development, hosting',
		download: 'Download',
		downloadCount: 'Download count',
		downloadGameLog: 'Download game log',
		downloadingPackage: 'Downloading package from storage…',
		drop: 'Drop',
		duplicateUserName: 'A user with this name is already logged on the server!',
		duration: 'Duration',
		editTable: 'Edit game table',
		editTables: 'Edit player tables',
		enableSound: 'Enable sound',
		enter: 'Sign in',
		enterPin: 'Enter PIN code to join the game',
		errorBadPackage: 'Bad question package!',
		errorDuplicateGameName: 'A game with the provided name already exists!',
		errorHappened: 'Error',
		errorInternalServerError: 'Cannot create the game because of the server error!',
		errorObsoleteVersion: 'Your game version is outdated. Update the game',
		errorPackageNotFound: 'Cannot create the game because the question package was not found!',
		errorServerNotReady: 'Server is not ready to start a game',
		errorServerUnderMaintainance: `Server is under maintenance! Please reconnect after a while.
		We apologize for any inconvenience.`,
		errorTolerant: 'right to make a mistake',
		errorTooManyGames: 'The maximum number of running games on the server has been exceeded! Please, try again later.',
		errorUnknownError: 'Unable to create the game for unknown reason!',
		exit: 'Exit',
		exitConfirmation: 'Really exit?',
		exitError: 'Cannot exit game!',
		exitFromGame: 'Leave game',
		externalMediaDetected: 'External Media Detected',
		externalMediaDescription: 'This content is not loaded automatically:',
		externalMediaLoad: 'Load External Media',
		failedToCompleteNegotiationWithTheServer: 'Failed to complete negotiation with the server',
		failedToFetch: 'Cannot send request to server. Check your internet connection, contact your internet provider, or consider possible regional restrictions',
		falseStarts: 'False starts',
		falseStartsHint: 'you can not press the button before the end of the question reading',
		female: 'woman',
		file: 'File with questions',
		fileIsTooBig: 'File exceeds maximum size!',
		fileNonReadable: 'Cannot open file. Maybe it has been changed. Pleae select it again',
		filter: 'Filter',
		final: 'Final',
		floatingControls: 'Auto-hide game controls',
		font: 'Font',
		forbiddenNickname: 'This nickname is forbidden on the server!',
		freedSlot: '{0} freed slot with {1}',
		freeTable: 'Free table',
		friendsPlay: 'Play with friends',
		from: 'from',
		fullScreen: 'Full screen mode',
		game: 'Game',
		gameAuthor: 'Game author',
		gameButton: 'Game button',
		gameButtonKey: 'Game button key',
		gameClosed: 'Game closed by server due to inactivity',
		gameCount: 'Game count',
		gameDuration: 'Game duration',
		gameError: 'Game error',
		gameFinished: 'Game finished',
		gameInfo: 'Game info',
		gameJoin: 'Join game',
		gameManageHint: 'Change round',
		gameName: 'Name',
		gameNameMustBeSpecified: 'Game name required',
		gameNotFound: 'Game not found',
		gameLoading: 'Game loading…',
		gameOf: 'Game by',
		gameResults: 'Game results',
		games: 'Games',
		gameStarted: 'Game started',
		gameStatistics: 'Game statistics',
		gamesTitle: 'Find a room in the list or create a new one',
		gameThemes: 'Game themes',
		gameType: 'Game type',
		gameTypeClassicTableHint: 'Table: questions are selected by players. Main question type: with button',
		gameTypeClassicThemeListHint: 'Theme list: themes are removed and the last one is played. Main question type: for all with stake',
		gameTypeQuizTableHint: 'Table: questions are played sequentially. Main question type: for all',
		gameTypeQuizThemeListHint: 'Theme list: questions are played sequentially. Main question type: for all',
		gameTypeSimpleTableHint: 'Table: questions are played sequentially. Main question type: with button',
		gameTypeSimpleThemeListHint: 'Theme list: themes are removed and the last one is played. Main question type: for all with stake',
		gameTypeShowGameThemes: 'Round themes are shown before the game starts',
		gameTypeTurnTakingTableHint: `Table: questions are selected by players. Main question type: for yourself.
		After each question, the turn passes to the next player`,
		gameTypeTurnTakingThemeListHint: 'Theme list: themes are removed and the last one is played. Main question type: for all with stake',
		getPin: 'PIN-code',
		giveTurn: 'Change active player',
		giveTurnHint: 'Select new active player',
		greeting: 'Welcome to SIGame!',
		hideAnswers: 'Hide answers',
		hideChat: 'Hide chat',
		hintShowman: 'Provide right answers to the showman in advance',
		host: 'Host',
		hostNameChanged: 'Game host has been changed by {0} to {1}',
		hour: 'h',
		hours2: 'h',
		hours5: 'h',
		howToPlay: 'How to play',
		html: 'HTML',
		human: 'Human',
		humanPlayers: 'Humans',
		iAmRightFemale: 'I am right!',
		iAmRightMale: 'I am right!',
		iDisagree: 'I disagree!',
		iDisagreeHint: 'Disagree with someone else answer',
		images: 'Images',
		imageTime: 'Image display',
		info: 'Info',
		inputAnswer: 'Enter answer',
		inputNumber: 'Enter number',
		invalidNameEmpty: 'Name cannot be empty or contain only spaces',
		invalidNameCharacters: 'Name contains invalid characters. Only letters, numbers, spaces, dashes, underscores, dots, and @ symbol are allowed',
		invalidNameLength: 'Name must be between 1 and 30 characters long',
		invalidValueRange: 'Value must be between {0} and {1}',
		inviteLink: 'Invite link',
		inviteLinkCopied: 'Invite link copied to clipboard!',
		ignoreWrong: 'Subtract points for a wrong answer',
		isRightValidateIt: 'is correct. Decide: should the answer be accepted?',
		joinAsPlayer: 'Player',
		joinAsPlayerHint: 'Join as player',
		joinAsShowman: 'Showman',
		joinAsShowmanHint: 'Join as showman',
		joinAsViewer: 'Viewer',
		joinAsViewerHint: 'Join as viewer',
		joinByPin: 'Join by PIN-code',
		joinError: 'Cannot join game',
		joiningGame: 'Joining game…',
		joinLobby: 'Online game',
		joinMode: 'Join mode',
		joinModeAnyRole: 'Any role',
		joinModeForbidden: 'Forbidden',
		joinModeViewer: 'Only as viewer',
		keyRight: 'Right arrow',
		keys: 'Keys',
		keySpace: 'Space',
		kick: 'Kick',
		language: 'Language',
		languageDefault: '(default)',
		languageEn: 'English',
		languageRu: 'Русский',
		languageSr: 'Srpski',
		latestGames: 'Latest games',
		lawIssue: 'Legal issue',
		library: 'Library',
		librarySearchAll: '(all)',
		librarySearchLessOrEqual: 'less than or equal to',
		librarySearchMoreOrEqual: 'greater than or equal to',
		librarySearchNotSet: '(not set)',
		librarySelect: 'Select',
		libraryTitle: 'Questions library',
		license: 'License',
		licenseInfo: 'License: any use of the game is allowed with the condition of attribution.',
		loading: 'Loading',
		logo: 'Logo',
		mainMenuSound: 'Main menu sound',
		makeAnswer: 'Answer',
		male: 'man',
		managed: 'Managed game',
		managedHint: 'The game continues only by pressing the "Next" button',
		media: 'Media',
		mediaLoadedMark: 'Media loaded',
		mediaPreloadProgress: 'Media preload progress',
		members: 'Members',
		menu: 'Menu',
		message: 'Message',
		methodNotAllowed: 'Wrong operation method',
		minMaxInRound: 'Minimum or maximum in round',
		minute: 'min',
		minutes2: 'min',
		minutes5: 'min',
		myRole: 'My role',
		name: 'Name',
		new: 'New',
		newGame: 'New game',
		news: 'News',
		next: 'Next',
		no: 'No',
		nofalsestart: 'without false starts',
		nominal: 'Nominal',
		noPackages: 'No packages found',
		noPackagesSteam: 'No subscribed packages found. Go to Workshop and subscribe to some packages to play',
		notReadyFemale: 'I am not ready for the game',
		notReadyMale: 'I am not ready for the game',
		noRisk: 'no risk',
		noRiskQuestion: 'No risk question',
		answerDeviation: 'Answer deviation',
		notSet: 'Not set',
		noWarranty: `The game is distributed free of charge.
		The author does not guarantee the correct operation of the game in arbitrary conditions
		and is not responsible for any consequences from the game usage.`,
		number: 'Number',
		ofGames: 'games count',
		openFile: 'Open file',
		openLibrary: 'Go to library',
		oral: 'oral',
		oralAnswerHint: 'Give the answer!',
		oralGame: 'Oral game',
		pointAnswerHint: 'Select a point on the image',
		oralGameDisabled: 'Oral game mode has been disabled by {0}',
		oralGameEnabled: 'Oral game mode has been enabled by {0}',
		oralGameHint: 'If the showman is a human. Good setting for live streaming. Players make a choice and give answers by voice',
		oralPlayersActions: 'Allow players to make actions in oral game',
		orByFilling: 'or by filling',
		other: 'Other',
		packageIsTooBig: 'Package exceeds maximum size!',
		package: 'Package',
		packages: 'Packages',
		packageAuthor: 'Author',
		packageAuthors: 'Package authors',
		packageComments: 'Package comments',
		packageDate: 'Package creation date',
		packageDifficulty: 'Difficulty',
		packageFileWarning: `By uploading a package to the server, you confirm that you are the package author or have rights to upload it.
Package authors are responsible for package content. The package will be automatically deleted from the server after the game ends`,
		packageQualityMark: 'Quality mark',
		packagePublishedDate: 'Publish date',
		packagePublisher: 'Publisher',
		packageRestriction: 'Restriction',
		packageSources: 'Package sources',
		packageSubject: 'Topic',
		page: 'Page',
		partialImages: 'Partial question images',
		partialImagesHint: 'When playing without false starts, question images are displayed in portions',
		partialImageTime: 'Partial image display',
		partialText: 'Partial question text',
		partialTextHint: 'When playing without false starts, question text is displayed in portions',
		pass: 'Pass',
		password: 'Password',
		passwordRequired: 'Password is required to enter',
		pause: 'Pause',
		penaltyNone: 'No penalty (no risk)',
		penaltySubtractPoints: 'Subtract points',
		pickAnEmoji: 'Pick an emoji',
		pin: 'PIN-code',
		pinCopied: 'PIN-code copied',
		playAllQuestionsInFinalRound: 'Play all questions',
		player: 'Player',
		players: 'Players',
		playerAnswerLabel: '{0} answer:',
		playersAnswer: 'Player answer',
		playerScoreChanged: '{0} changed {1} score from {2} to {3}',
		playWithBots: 'Play with bots',
		playWithFriends: 'Play with friends',
		position: '#',
		preloadRoundContent: 'Preload media content for all persons at the beginning of the round',
		presents: 'presents',
		presentsPlural: 'present',
		price: 'Price',
		profile: 'Profile',
		publisher: 'Publisher',
		question: 'Question',
		questionAuthors: 'Question authors',
		questionComments: 'Question comments',
		questionComplain: 'Complain about question',
		questionCount: 'Question count',
		questionCountPerTheme: 'Question count (per theme)',
		questionEditor: 'Question editor',
		questionPackage: 'Question package',
		questionPenalty: 'Penalty for wrong answer',
		questionReadingSpeed: 'Question reading speed',
		questionRemoved: '{0} removed question {1}, {2}',
		questionRestored: '{0} restored question {1}, {2}',
		questions: 'Questions',
		questionsPlayed: 'Questions played',
		questionSources: 'Question sources',
		questionTypeForAll: 'For all',
		questionTypeForAllHint: 'Question is played by all players',
		questionTypeForAllWithStake: 'For all with stake',
		questionTypeForAllWithStakeHint: 'Everyone makes a stake and plays',
		questionTypeForYourself: 'For yourself',
		questionTypeForYourselfHint: 'Question is played by current player',
		questionTypeSecret: 'With secret',
		questionTypeSecretHint: 'Question is given to player and they should answer it',
		questionTypeSecretNoQuestion: 'With secret without a question',
		questionTypeSecretPublicPrice: 'With secret and announced cost',
		questionTypeSimple: 'With button',
		questionTypeSimpleHint: 'Question is answered by player who pressed the button',
		questionTypeStake: 'With stake',
		questionTypeStakeHint: 'Question is played by player who made the highest stake. All-in can be overcome by another all-in',
		randomThemes: 'Random themes',
		rateGame: 'Rate game',
		reviewPackage: 'Review package',
		reactions: 'Reactions',
		readyFemale: 'I am ready for the game',
		readyMale: 'I am ready for the game',
		reloadPage: 'Reload page',
		replacedSlot: '{0} replaced {1} with {2}',
		replaceWith: 'Replace with',
		replic_Answer: '{0}, what is your answer?;{0}, your answer?;{0}?;{0}, answer!;{0}, I am listening to you;{0}, please, answer',
		replic_MakeStake: '{0}, what\'s your stake?;{0}, make your stake',
		replic_RoundSkippedNoPlayers: 'There are no players who can play the next round. So, the round is skipped',
		replic_SelectAnswerOption: '{0}, select answer option on table',
		replic_SelectPlayer: '{0}, who will you give the question to?',
		replic_SelectQuestion: '{0}, please select the question!;{0}, make a choice!;{0}, it\'s your choice;{0}, you\'re selecting the next question',
		replic_ShowmanGreeting: 'Greetings, ladies and gentlement, this is SIGame!',
		replic_UnsupportedQuestion: 'This question should be played manually. The game will continue after small delay',
		requestedAppellation: '{0} requested appellation',
		resetToDefaults: 'Reset to defaults',
		resetToDefaultsHint: 'Resets all settings to their initial values',
		removeContentItem: 'Remove content item',
		removeOption: 'Remove option',
		removeScreen: 'Remove screen',
		restriction: 'Restriction',
		restrictionIssue: 'Restriction issue (age, etc.)',
		results: 'Results',
		resume: 'Resume',
		reviews: 'Reviews',
		rightAnswer: 'Right answer',
		rightAnswers: 'Right answers',
		role: 'Role',
		room: 'Room',
		round: 'Round',
		roundAuthors: 'Round authors',
		roundComments: 'Round comments',
		roundEndedEmpty: 'Round ended because there are no questions left',
		roundEndedManual: 'Round ended manually',
		roundEndedTimeout: 'Round ended due to timeout',
		roundCount: 'Round count',
		rounds: 'Rounds',
		roundsAndThemes: 'Round and themes',
		roundSources: 'Round sources',
		roundThemes: 'Round themes',
		roundTypeTable: 'Table',
		rules: 'Rules',
		rulesClassic: 'Classical',
		rulesRemoveThemes: 'Players remove themes one by one. Question in the last theme is played',
		rulesSequential: 'Questions are played sequentially',
		score: 'Score',
		scoreEarned: 'Score earned',
		scoreFactor: 'Price factor',
		scoreLost: 'Score lost',
		screenDuration: 'Duration (s)',
		search: 'Search',
		searchGames: 'Rooms search',
		searchHint: 'Start search to see rooms list',
		sec: 's',
		second: 'sec',
		seconds2: 'sec',
		seconds5: 'sec',
		select: 'Select…',
		selectAnswerer: 'Select a player to give the question to',
		selectAvatar: 'Select avatar',
		selectFirstPlayer: 'Select a person to start round',
		selectionMode: 'Transfer mode',
		selectStaker: 'Select a person to make a stake',
		selectThemeDeleter: 'Select a person to delete a theme',
		send: 'Send',
		sendingPackage: 'Sending package to server…',
		savePackage: 'Save package',
		server: 'Server',
		serverLicense: 'Server license',
		setAnswererSelectAny: 'To anyone',
		setAnswererSelectExceptCurrent: 'To everyone except oneself',
		setChooser: '{0} made {1} an active player',
		setJoinMode: 'updated room join mode to',
		settings: 'Settings',
		set: 'Set',
		setHost: 'Set as host',
		sex: 'Sex',
		showAnswers: 'Show answers',
		showChat: 'Show chat',
		showman: 'Showman',
		showVideoAvatars: 'Show video avatars',
		singlePlay: 'Single game',
		size: 'Size',
		sort: 'Sort',
		sound: 'Sound',
		soundApp: 'Application sound',
		sounds: 'Sounds',
		soundsUpload: 'Upload custom sound',
		soundsReset: 'Reset to default',
		soundAnswerWrong: 'Wrong answer',
		soundApplauseBig: 'Big applause',
		soundApplauseFinal: 'Final applause',
		soundApplauseSmall: 'Small applause',
		soundFinalDelete: 'Final round theme removal',
		soundFinalThink: 'Final round thinking',
		soundMainMenu: 'Main menu',
		soundQuestionAll: 'Question for all',
		soundQuestionForYourself: 'Question for yourself',
		soundQuestionNoAnswers: 'No answer',
		soundQuestionSecret: 'Secret question',
		soundQuestionStake: 'Stake question',
		soundQuestionStakeAll: 'All-in stake question',
		soundRoomEntry: 'Room entry',
		soundRoundBegin: 'Round',
		soundRoundThemes: 'Round themes',
		soundRoundTimeout: 'Round timeout',
		sources: 'Sources',
		sourcesInfo: 'Game source code page.',
		soundVolume: 'Sound volume',
		sport: 'Simple',
		sportPlural: 'Simple',
		started: 'Started',
		startGame: 'Create',
		startGameHint: 'Start game without waiting for persons readiness',
		status: 'Status',
		steamWorkshop: 'Steam Workshop',
		supportInfo: 'Support page.',
		symbolsPerSecond: 'symbols per second',
		syntaxError: 'Syntax error',
		table: 'Table',
		tableHint: `To answer the question, press the button after the frame lights up on the screen.
		The game will start when all participants are ready`,
		tableLogoAuthor: 'by Vladimir Khil',
		tags: 'Tags',
		text: 'Text',
		textColor: 'Text color',
		theGameWillStartIn: 'The game will start after',
		thePlayerThinksThatHisHerAnswer: 'The player thinks the answer is correct',
		theme: 'Theme',
		themeAuthors: 'Theme authors',
		themeCount: 'Theme count (per round)',
		themeCountFinal: 'Theme count (in final round)',
		includeFinalRound: 'Include final round',
		authorName: 'Author name',
		themeList: 'Theme list',
		themeSources: 'Theme sources',
		time: 'Time',
		timeForBlockingButton: 'Button cooldown (when false starts are enabled)',
		timeForChoosingFinalTheme: 'Choosing theme (removal)',
		timeForChoosingQuestion: 'Choosing question',
		timeForFinalThinking: 'Answering on question for all',
		timeForGivingACat: 'Selecting another player (giving question)',
		timeForMakingStake: 'Making stake',
		timeForPrintingAnswer: 'Answering after pressing the button',
		timeForRightAnswer: 'Displaying right answer',
		timeForShowmanDecisions: 'Showman decisions',
		timeForThinkingOnQuestion: 'Pressing button (answering border shrinking)',
		timeForThinkingOnSpecial: 'Answering on special question',
		timeOfRound: 'Round',
		to: 'to',
		tooManyGamesByIp: 'Too many games on a single client IP!',
		tooManyRequests: 'Too many requests. Please try again later',
		topPackages: 'Weekly top packages',
		total: 'Total:',
		trends: 'Trends',
		quiz: 'Quiz',
		turnTaking: 'Turn-taking',
		tv: 'Classic',
		tvPlural: 'Classic',
		type: 'Type',
		unban: 'Remove ban',
		unknownError: 'Unknown error',
		unsupportedBrowser: 'Your browser is not supprted. Please, update or replace it',
		unsupportedMediaType: 'Unsupported media type',
		uploadingImageError: 'Avatar sending error',
		uploadingPackageError: 'Package sending error',
		useApellations: 'Answer apellations',
		useApellationsHint: 'Buttons "I am right" and "I disagree"',
		useProxy: 'Use proxy connection',
		useProxyHint: 'When available',
		useProxyOnErrors: 'In case of connection errors, try to enable or disable proxy in settings',
		usedComponents: 'Game components and licenses:',
		userPackages: '',
		users: 'Players',
		userUnbanned: 'User {0} was unbanned',
		validateAnswer: 'Is the answer correct?',
		video: 'Video',
		videoAvatar: 'Video avatar',
		viewer: 'Viewer',
		viewers: 'Viewers',
		viewMode: 'View mode',
		editMode: 'Edit mode',
		enableEditMode: 'Enable edit mode',
		editModeDisclaimer: 'Edit mode is experimental. Use at your own risk. Save frequently.',
		downloadPackageStatistics: 'Download package statistics',
		loadingStatistics: 'Loading statistics...',
		completedGames: 'Completed games: {0} of {1} ({2}%)',
		answerTries: 'Answer tries',
		voiceChat: 'Voice chat',
		webCameraUrl: 'Web camera url',
		welcomeTitle: 'Select an action',
		managedGameEnabled: 'Managed game mode has been enabled by {0}',
		managedGameDisabled: 'Managed game mode has been disabled by {0}',
		falseStartEnabled: 'False start mode has been enabled by {0}',
		falseStartDisabled: 'False start mode has been disabled by {0}',
		readingSpeedChanged: 'Reading speed has been changed by {0} to {1}',
		partialTextEnabled: 'Partial text mode has been enabled by {0}',
		partialTextDisabled: 'Partial text mode has been disabled by {0}',
		partialImagesEnabled: 'Partial images mode has been enabled by {0}',
		partialImagesDisabled: 'Partial images mode has been disabled by {0}',
		partialImageTimeChanged: 'Partial image display time has been changed by {0} to {1}',
		useApellationsEnabled: 'Appellations have been enabled by {0}',
		useApellationsDisabled: 'Appellations have been disabled by {0}',
		blockingTimeChanged: 'Button blocking time has been changed by {0} to {1}',
		displayLabelsEnabled: 'Answer option labels have been enabled by {0}',
		displayLabelsDisabled: 'Answer option labels have been disabled by {0}',
		withButton: 'With button',
		withoutPassword: 'Without password',
		withStep: 'with step',
		writeGameLog: 'Write game log',
		wrongAnswer: 'Wrong answer',
		wrongAnswers: 'Wrong answers',
		wrongGameSettings: 'Wrong game settings!',
		yes: 'Yes',
		youAreKicked: 'You have been kicked from the game!',
		yourName: 'Your name',
		custom: 'Custom',
		enterAnswer: 'Enter answer',
		enterAuthorName: 'Enter author name',
		enterCustomQuestionType: 'Enter custom question type',
		enterSource: 'Enter source',
		enterTag: 'Enter tag',
		enterTextContent: 'Enter text content...',
		enterWrongAnswer: 'Enter wrong answer'
	},
	ru: {
		about: [
			'SIGame — интеллектуальная викторина, в которой каждый может проверить свои знания и скорость реакции и сразиться с оппонентами.',
			`Правила игры очень просты: все вопросы в игре поделены по темам, и у каждого вопроса в теме есть своя стоимость.
	У каждого игрока имеется персональный счёт, который в начале игры равен 0.
	Звучит вопрос, после которого на экране появляется рамка, показывающая, что можно отвечать.
	Если игрок знает ответ, он может нажать на красную кнопку. Тот из игроков, кто нажмёт на кнопку ранее
	(и не допустит фальстарта), и даёт ответ. В случае верного ответа стоимость вопроса прибавляется к счёту игрока;
	в случае неверного — снимается со счёта. В последнем случае другие игроки снова могут попытать счастья и нажать на кнопку для ответа.`,
			`Также в игре могут встретиться специальные вопросы. В "Вопросе со ставкой" участники торгуются за вопрос, и отвечает на него тот игрок,
	кто поставит наибольшую сумму. При этом "Ва-банк" (т.е. ставка всей суммы на кон) может быть перебит только другим "Ва-банком".`,
			`"Вопрос с секретом" открывший его участник должен передать другому участнику. Получивший его игрок должен (если это заложено в вопросе)
	выбрать стоимость вопроса и ответить на него. Тема вопроса может отличаться от основной темы, в которой находился вопрос.`,
			'На "Вопрос для себя" отвечает открывший его игрок.',
			`В игре также может быть финальный раунд, в котором каждый из игроков делает ставку. Звучит вопрос, даётся время на размышление,
	и каждый из игроков письменно сдаёт свой ответ. После этого оглашается правильный ответ, и каждый из игроков получает или теряет деньги.`,
			'Победителем игры становится игрок, набравший после последнего вопроса наибольшую сумму.',
			'Игровую кнопку можно также активировать при помощи назначенной клавиши или правой кнопки мыши.'
		],
		aboutAuthor: 'Автор',
		aboutSupport: 'Техническая поддержка',
		aboutTitle: 'Об игре',
		acceptLicense: 'Принять лицензию',
		addedNewSlot: '{0} добавил новый слот игрока',
		addOption: 'Добавить вариант',
		addContentItem: 'Добавить элемент контента',
		addScreen: 'Добавить экран',
		addTable: 'Добавить стол',
		all: 'Все',
		allIn: 'ВА-БАНК!',
		allowEveryoneToPlayHiddenStakes: 'Играют все игроки',
		allowEveryoneToPlayHiddenStakesHint: 'даже с 0 или отрицательным счётом',
		answer: 'Ответ',
		answerChecking: 'Проверка ответа',
		answerOptions: 'Варианты ответа',
		answerType: 'Тип ответа',
		answerTypeSelect: 'Выбор из вариантов',
		anyonePlay: 'Игра со случайными соперниками',
		apellateAnswer: 'Апеллировать свой ответ',
		apellation: 'Апелляция',
		appellationMark: 'Запрошена апелляция',
		apiCallsQuotaExceeded: 'Превышен лимит запросов. Попробуйте позже',
		appName: 'SIGame',
		appUser: 'SIGame',
		ascending: 'по возрастанию',
		attachContentToTable: 'Добавлять комментарии темы и правильный ответ на табло',
		audio: 'Аудио',
		audioLoadError: 'Ошибка загрузки аудио',
		authorInfo: 'Владимир Хиль',
		authors: 'Авторы',
		avatar: 'Аватар',
		avatarLoadError: 'Ошибка отправки аватара',
		backgroundColor: 'Цвет фона',
		backgroundImage: 'Фоновое изображение',
		badPackage: 'Плохой пакет вопросов!',
		ban: 'Забанить',
		bannedNotification: '{0} выгнал {1} из игры',
		bannedList: 'Список забаненных',
		blocked: '(Заблокирован)',
		bot: 'Бот',
		buttonPressMode: 'Режим нажатия кнопки',
		buttonPressModeFirstWins: 'Кто первым нажал (по версии сервера)',
		buttonPressModeFirstWinsClient: 'Кто первым нажал (по версии клиента)',
		buttonPressModeRandomWithinInterval: 'Рандом из ранних нажавших',
		by: 'от',
		byGame: 'игрой',
		cancel: 'Отмена',
		cancelAnswer: 'Отменить ответ игрока',
		cannotConnectToServer: 'Не удалось подключиться к серверу',
		changedSlotType: '{0} изменил тип слота игрока {1} на: {2}',
		changeSums: 'Изменить суммы',
		changeToBot: 'Заменить на бота',
		changeToHuman: 'Заменить на человека',
		chat: 'Чат',
		chooserMark: 'Метка выбирающего вопрос',
		close: 'Закрыть',
		comment: 'Комментарий',
		comments: 'Комментарии',
		common: 'Общее',
		complain: 'Пожаловаться',
		complainHint: 'В вопросе содержится орфографическая или фактическая ошибка',
		composer: 'Композитор',
		computer: 'Бот',
		computerAccountsMissing: 'Не загружены компьютерные аккаунты. Попробуйте перезагрузить игру',
		computerPlayers: 'Боты',
		connected: 'Подключился(лась) {0}',
		connectionClosed: 'Соединение с сервером разорвано!',
		connectionReconnecting: 'Соединение потеряно, пытаемся переподключиться…',
		connectionReconnected: 'Соединение восстановлено!',
		contactUri: 'Контакты авторов',
		content: 'Контент',
		cookiesConfirm: 'Принять',
		cookiesWarning: 'Это приложение использует куки-файлы. Оставаясь на странице, вы соглашаетесь с этим',
		copyrightIssue: 'Нарушение авторских прав',
		copyText: 'Скопировать текст в буфер обмена',
		corruptedPackage: 'Пакет вопросов повреждён!',
		created: 'Создана',
		createOwnPackage: 'Создать свой пакет',
		createPackage: 'Создать пакет',
		creatingGame: 'Создание игры…',
		date: 'Дата',
		default: 'Обычный',
		defaultFont: '(по умолчанию)',
		defaultShowman: 'Леонардо да Винчи',
		delete: 'Удалить',
		deleteAvatar: 'Удалить аватар',
		deletedSlot: '{0} удалил слот игрока {1}',
		deleteTable: 'Удалить стол',
		demoAbout: `SIGame — интеллектуальная викторина, в которой вы можете проверить свои знания и скорость реакции против соперников.
	Скорость и знание — ключ к победе.
	Вопрос озвучивается, после чего на экране появляется рамка, показывающая, что можно нажимать кнопку и отвечать`,
		demoCorrectAnswer: 'Вы дали правильный ответ! Ваш счёт увеличен на стоимость вопроса',
		demoFalseStarts: 'Если игра ведётся без фальстартов, то рамка (и возможность нажать кнопку) появятся сразу вместе с вопросом',
		demoFinished: 'Демо-режим завершён. Спасибо! Удачной вам игры!',
		demoGameRules: 'Отвечая на вопросы, вы зарабатываете очки. В игре побеждает тот, кто наберёт больше очков',
		demoGiveAnswer: 'Теперь напечатайте ответ на вопрос. Напишите: ОТВЕТ и нажмите кнопку Отправить',
		demoOpponents: `Вы можете сыграть с ботами или пригласить друзей.
		Можно играть на готовых вопросах в игре, использовать вопросы сторонних авторов или написать свои`,
		demoOtherContent: `В вопросах могут быть изображения, аудио или видео.
		Могут повстречатьcя вопросы с вариантами ответа, и нужно будет выбрать правильный вариант из них`,
		demoOtherQuestions: `В игре могут быть и другие вопросы, например, с секретом или со ставкой.
		Для каждого из спецвопросов будут объяснения в процессе игры`,
		demoQuestion: `Это демо-вопрос. Нажмите кнопку, чтобы ответить.
	Если вы нажмёте кнопку раньше, чем появится рамка, это будет фальстарт, и ваша кнопка некоторое время не будет работать.
	Если вы нажмёте кнопку, но другой игрок опередит вас, то ваша кнопка также будет заблокирована.
	Первый игрок, который нажмёт кнопку, будет отвечать на вопрос`,
		demoWelcome: `Добро пожаловать в SIGame!
	Вы всегда можете выйти из демо-режима по кнопке "Выход" в углу экрана.
	Для начала демонстрации нажмите кнопку "Готов" (зелёную галочку)`,
		demoWrongAnswer: 'Вы дали неправильный ответ! Ваш счёт уменьшен на стоимость вопроса',
		descending: 'по убыванию',
		disconnected: '{0} отключился(лась)',
		difficulty: 'Сложность',
		disableSound: 'Отключить звук',
		siStorageDisclaimer: `Внимание! В данном разделе представлены материалы сторонних авторов.
	Авторы пакетов в библиотеке несут ответственность за содержание пакетов, их достоверность и соответствие закону`,
		displayAnswerOptionsLabels: 'Показывать буквы вариантов ответа',
		displayAnswerOptionsOneByOne: 'Показывать варианты ответа по очереди',
		displaySources: 'Показывать источники вопросов',
		donate: 'Донат',
		donateComment: `Донаты не обязательны и тратятся только на оплату хостинга и домена.
	 Проект некоммерческий и существует в образовательных целях.
	 Вся функциональность игры доступна бесплатно - донаты не влияют на игровой процесс
	 и не используются для доступа к дополнительным функциям игры. Спасибо за поддержку!`,
		donateServersHosting: 'ДОНАТ: развитие, хостинг',
		download: 'Скачать',
		downloadCount: 'Число скачиваний',
		downloadGameLog: 'Скачать журнал игры',
		downloadingPackage: 'Загрузка пакета из хранилища…',
		drop: 'Сбросить',
		duplicateUserName: 'Пользователь с таким именем уже вошёл на сервер!',
		duration: 'Продолжительность',
		editTable: 'Редактировать табло',
		editTables: 'Редактировать столы',
		enableSound: 'Включить звук',
		enter: 'Вход',
		enterPin: 'Введите ПИН-код для входа в игру',
		errorBadPackage: 'Плохой пакет вопросов!',
		errorDuplicateGameName: 'Игра с таким именем уже существует!',
		errorHappened: 'Ошибка',
		errorInternalServerError: 'Не удалось создать игру на сервере из-за ошибки на сервере!',
		errorObsoleteVersion: 'Ваша версия игры устарела. Обновите игру',
		errorPackageNotFound: 'Не удалось создать игру на сервере, так как не был обнаружен игровой пакет!',
		errorServerNotReady: 'Сервер не готов начать игру',
		errorServerUnderMaintainance: `Производится обслуживание сервера! Пожалуйста, подключитесь через некоторое время.
	Приносим извинения за доставленные неудобства.`,
		errorTolerant: 'право на ошибку',
		errorTooManyGames: 'Превышено максимальное количество запущенных игр на сервере! Пожалуйста, подождите.',
		errorUnknownError: 'Не удалось создать игру по неизвестной причине!',
		exit: 'Выход',
		exitConfirmation: 'Действительно выйти?',
		exitError: 'Не удалось выйти из игры!',
		exitFromGame: 'Выйти из игры',
		externalMediaDetected: 'Обнаружено внешнее медиа',
		externalMediaDescription: 'Этот контент не загружается автоматически:',
		externalMediaLoad: 'Загрузить внешнее медиа',
		failedToCompleteNegotiationWithTheServer: 'Не удалось завершить переговоры с сервером',
		failedToFetch: `Не удалось отправить запрос на сервер. Проверьте Интернет-соединение,
		обратитесь к Интернет-провайдеру или учтите возможные региональные ограничения (блокировки)`,
		falseStarts: 'Фальстарты',
		falseStartsHint: 'нельзя нажимать на кнопку до окончания чтения вопроса',
		female: 'женщина',
		file: 'Файл с вопросами',
		fileIsTooBig: 'Файл превышает максимальный размер!',
		fileNonReadable: 'Невозможно открыть файл. Возможно, он был изменён. Пожалуйста, выберите его ещё раз',
		filter: 'Фильтр',
		final: 'Финал',
		floatingControls: 'Автоматическое скрытие элементов управления',
		font: 'Шрифт',
		forbiddenNickname: 'На сервере запрещено использование такого ника!',
		freedSlot: '{0} освободил слот с {1}',
		freeTable: 'Освободить стол',
		friendsPlay: 'Играть с друзьями',
		from: 'от',
		fullScreen: 'Полноэкранный режим',
		game: 'Игра',
		gameAuthor: 'Автор программы',
		gameButton: 'Игровая кнопка',
		gameButtonKey: 'Клавиша игровой кнопки',
		gameClosed: 'Игра завершена сервером по причине неактивности',
		gameCount: 'Всего игр',
		gameDuration: 'Общая продолжительность',
		gameError: 'Ошибка игры',
		gameFinished: 'Игра окончена',
		gameInfo: 'Информация об игре',
		gameJoin: 'Вход в игру',
		gameManageHint: 'Поменять раунд',
		gameName: 'Название',
		gameNameMustBeSpecified: 'Необходимо задать название игры',
		gameNotFound: 'Игра не найдена',
		gameLoading: 'Идёт загрузка игры…',
		gameOf: 'Игра от',
		gameResults: 'Результаты игры',
		games: 'Игры',
		gameStarted: 'Игра началась',
		gameStatistics: 'Статистика игры',
		gamesTitle: 'Найдите комнату в списке или создайте новую',
		gameThemes: 'Темы игры',
		gameType: 'Тип игры',
		gameTypeClassicTableHint: 'Таблица: вопросы выбираются игроками. Основной тип вопроса: с кнопкой',
		gameTypeClassicThemeListHint: 'Список тем: удаляются темы и играется последняя. Основной тип вопроса: для всех со ставкой',
		gameTypeQuizTableHint: 'Таблица: вопросы играются по очереди. Основной тип вопроса: для всех',
		gameTypeQuizThemeListHint: 'Список тем: вопросы играются по очереди. Основной тип вопроса: для всех',
		gameTypeSimpleTableHint: 'Таблица: вопросы играются по очереди. Основной тип вопроса: с кнопкой',
		gameTypeSimpleThemeListHint: 'Список тем: удаляются темы и играется последняя. Основной тип вопроса: для всех со ставкой',
		gameTypeShowGameThemes: 'Перед началом игры показываются темы раундов',
		gameTypeTurnTakingTableHint: `Таблица: вопросы выбираются игроками. Основной тип вопроса: для себя.
		После каждого вопроса ход переходит к следующему игроку`,
		gameTypeTurnTakingThemeListHint: 'Список тем: удаляются темы и играется последняя. Основной тип вопроса: для всех со ставкой',
		getPin: 'ПИН-код',
		giveTurn: 'Передать ход игроку',
		giveTurnHint: 'Выберите, кому передать ход',
		greeting: 'Добро пожаловать в SIGame!',
		hideAnswers: 'Скрыть ответы',
		hideChat: 'Скрыть чат',
		hintShowman: 'Сообщать ведущему правильные ответы заранее',
		host: 'Хост',
		hostNameChanged: 'Хост игры был изменён {0} на {1}',
		hour: 'ч',
		hours2: 'ч',
		hours5: 'ч',
		howToPlay: 'Как играть',
		html: 'HTML',
		human: 'Человек',
		humanPlayers: 'Люди',
		iAmRightFemale: 'Я права!',
		iAmRightMale: 'Я прав!',
		iDisagree: 'Я против!',
		iDisagreeHint: 'Оспорить чужой ответ',
		ignoreWrong: 'Снимать очки за неверный ответ',
		images: 'Изображения',
		imageTime: 'Вывод изображения',
		info: 'Инфо',
		inputAnswer: 'Напишите ответ',
		inputNumber: 'Введите число',
		invalidNameEmpty: 'Имя не может быть пустым или содержать только пробелы',
		invalidNameCharacters: 'Имя содержит недопустимые символы. Разрешены только буквы, цифры, пробелы, дефисы, подчеркивания, точки и символ @',
		invalidNameLength: 'Имя должно содержать от 1 до 30 символов',
		invalidValueRange: 'Значение должно быть от {0} до {1}',
		inviteLink: 'Ссылка для входа',
		inviteLinkCopied: 'Ссылка скопирована',
		isRightValidateIt: 'верен. Примите решение: засчитать ли ответ?',
		joinAsPlayer: 'Игрок',
		joinAsPlayerHint: 'Войти игроком',
		joinAsShowman: 'Ведущий',
		joinAsShowmanHint: 'Войти ведущим',
		joinAsViewer: 'Зритель',
		joinAsViewerHint: 'Войти зрителем',
		joinByPin: 'Вход по ПИН-коду',
		joinError: 'Не удалось подключиться к игре',
		joiningGame: 'Подключение к игре…',
		joinLobby: 'Игра онлайн',
		joinMode: 'Режим входа',
		joinModeAnyRole: 'С любой ролью',
		joinModeForbidden: 'Вход запрещён',
		joinModeViewer: 'Только зрителем',
		keyRight: 'Стрелка вправо',
		keys: 'Клавиши',
		keySpace: 'Пробел',
		kick: 'Выгнать',
		language: 'Язык',
		languageDefault: '(по умолчанию)',
		languageEn: 'English',
		languageRu: 'Русский',
		languageSr: 'Srpski',
		latestGames: 'Последние игры',
		lawIssue: 'Нарушение закона',
		library: 'Библиотека',
		librarySearchAll: '(все)',
		librarySearchLessOrEqual: 'меньше или равна',
		librarySearchMoreOrEqual: 'больше или равна',
		librarySearchNotSet: '(не задано)',
		librarySelect: 'Выбрать',
		libraryTitle: 'Библиотека вопросов',
		license: 'Лицензия',
		licenseInfo: 'Лицензия: допускается любое использование игры с условием указания авторства.',
		loading: 'Загрузка',
		logo: 'Логотип',
		mainMenuSound: 'Мелодия главного меню',
		makeAnswer: 'Ответить',
		male: 'мужчина',
		managed: 'Управляемая игра',
		managedHint: 'Игра продолжается только по нажатию кнопки "Дальше"',
		media: 'Медиа',
		mediaLoadedMark: 'Мультимедиа загружено',
		mediaPreloadProgress: 'Загрузка медиа-контента',
		members: 'Участники',
		menu: 'Меню',
		message: 'Сообщение',
		methodNotAllowed: 'Неправильный способ операции',
		minMaxInRound: 'Минимум или максимум в раунде',
		minute: 'мин',
		minutes2: 'мин',
		minutes5: 'мин',
		myRole: 'Моя роль',
		name: 'Имя',
		new: 'Новые',
		newGame: 'Новая игра',
		news: 'Новости',
		next: 'Дальше',
		no: 'Нет',
		nofalsestart: 'без фальстартов',
		nominal: 'Номинал',
		noPackages: 'Пакеты не найдены',
		noPackagesSteam: 'Пакеты не найдены. Перейдите в Мастерскую Steam и подпишитесь на пакеты, которые хотите использовать в игре',
		notReadyFemale: 'Я не готова к игре',
		notReadyMale: 'Я не готов к игре',
		noRisk: 'без риска',
		noRiskQuestion: 'Вопрос без риска',
		answerDeviation: 'Допустимое отклонение',
		notSet: 'Не задана',
		noWarranty: `Игра распространяется бесплатно. Автор не гарантирует корректность работы игры в произвольных условиях
	и не несёт ответственности за любые последствия от использования игры.`,
		number: 'Число',
		ofGames: 'игр',
		openFile: 'Открыть файл',
		openLibrary: 'Перейти в библиотеку',
		oral: 'устная',
		oralAnswerHint: 'Отвечайте!',
		oralGame: 'Устная игра',
		pointAnswerHint: 'Выберите точку на изображении',
		oralGameDisabled: 'Устная игра отключена {0}',
		oralGameEnabled: 'Устная игра включена {0}',
		oralGameHint: 'Если ведущий – человек. Хорошо подходит для стримов. Игроки делают выбор и дают ответ голосом',
		oralPlayersActions: 'Разрешать игрокам делать выбор в устной игре',
		orByFilling: 'или по заполнению',
		package: 'Пакет',
		other: 'Другое',
		packageIsTooBig: 'Пакет превышает максимальный размер!',
		packages: 'Пакеты',
		packageAuthor: 'Автор',
		packageAuthors: 'Авторы пакета',
		packageComments: 'Комментарии пакета',
		packageDate: 'Дата создания пакета',
		packageDifficulty: 'Сложность',
		packageFileWarning: `Загружая пакет на сервер, вы подтверждаете, что являетесь автором пакета или имеете права на его загрузку.
Авторы пакетов несут ответственность за содержимое пакетов. Пакет будет автоматически удалён с сервера после окончания игры`,
		packageQualityMark: 'Контроль качества',
		packagePublishedDate: 'Дата публикации',
		packagePublisher: 'Издатель',
		packageRestriction: 'Ограничение',
		packageSources: 'Источники пакета',
		packageSubject: 'Тематика',
		page: 'Страница',
		partialImages: 'Частичный вывод изображений',
		partialImagesHint: 'При игре без фальстартов изображения выводятся порционно',
		partialImageTime: 'Вывод частичных изображений',
		partialText: 'Частичный вывод текста',
		partialTextHint: 'При игре без фальстартов текст выводится порционно',
		pass: 'Пас',
		password: 'Пароль',
		passwordRequired: 'Требуется пароль для входа',
		pause: 'Пауза',
		penaltyNone: 'Нет штрафа (без риска)',
		penaltySubtractPoints: 'Снимать очки',
		pickAnEmoji: 'Выбрать эмодзи',
		pin: 'ПИН-код',
		pinCopied: 'ПИН-код скопирован',
		playAllQuestionsInFinalRound: 'Играть все вопросы',
		player: 'Игрок',
		players: 'Игроки',
		playerAnswerLabel: 'Ответ {0}:',
		playersAnswer: 'Ответ игрока',
		playerScoreChanged: '{0} изменил(а) сумму на счёте {1} с {2} на {3}',
		playWithBots: 'Играть с ботами',
		playWithFriends: 'Играть с друзьями',
		position: '№',
		preloadRoundContent: 'Предзагружать медиаконтент всем участникам в начале раунда',
		presents: 'представляет',
		presentsPlural: 'представляют',
		price: 'Стоимость',
		profile: 'Профиль',
		publisher: 'Издатель',
		question: 'Вопрос',
		questionAuthors: 'Авторы вопроса',
		questionComments: 'Комментарии к вопросу',
		questionComplain: 'Жалоба на вопрос',
		questionCount: 'Число вопросов',
		questionCountPerTheme: 'Число вопросов (в теме)',
		questionEditor: 'Редактор вопросов',
		questionPackage: 'Пакет вопросов',
		questionPenalty: 'Штраф за неверный ответ',
		questionReadingSpeed: 'Скорость чтения вопроса',
		questionRemoved: '{0} удалил вопрос {1}, {2}',
		questionRestored: '{0} восстановил вопрос {1}, {2}',
		questions: 'Вопросы',
		questionsPlayed: 'Сыграно вопросов',
		questionSources: 'Источники вопроса',
		questionTypeForAll: 'Для всех',
		questionTypeForAllHint: 'Вопрос играется всеми игроками',
		questionTypeForAllWithStake: 'Для всех со ставкой',
		questionTypeForAllWithStakeHint: 'Каждый делает ставку и играет на неё',
		questionTypeForYourself: 'Для себя',
		questionTypeForYourselfHint: 'Вопрос играет текущий игрок',
		questionTypeSecret: 'С секретом',
		questionTypeSecretHint: 'Вопрос отдаётся игроку, и тот обязан отвечать',
		questionTypeSecretNoQuestion: 'С секретом без вопроса',
		questionTypeSecretPublicPrice: 'С секретом и объявленной стоимостью',
		questionTypeSimple: 'С кнопкой',
		questionTypeSimpleHint: 'На вопрос отвечает игрок, нажавший на кнопку',
		questionTypeStake: 'Со ставкой',
		questionTypeStakeHint: 'На вопрос отвечает игрок, сделавший наибольшую ставку. Ва-банк можно перебить только ва-банком',
		quiz: 'Квиз',
		randomThemes: 'Случайный набор тем',
		rateGame: 'Оценить игру',
		reviewPackage: 'Оценить пакет',
		reactions: 'Реакции',
		readyFemale: 'Я готова к игре',
		readyMale: 'Я готов к игре',
		reloadPage: 'Обновить страницу',
		replacedSlot: '{0} заменил {1} на {2}',
		replaceWith: 'Заменить на',
		replic_Answer: '{0}, каков же ваш ответ?;{0}, ваш ответ?;{0}?;{0}, отвечайте!;{0}, я вас слушаю;{0}, прошу, отвечайте',
		replic_MakeStake: '{0}, ваша ставка?;{0}, сделайте ставку!',
		replic_RoundSkippedNoPlayers: 'У нас нет игроков, которые могут играть в следующем раунде. Поэтому мы пропускаем его',
		replic_SelectAnswerOption: '{0}, выберите вариант ответа на табло',
		replic_SelectPlayer: '{0}, кому вы отдадите вопрос?',
		replic_SelectQuestion: `{0}, выбирайте вопрос!;{0}, прошу вас!;{0}, выбирайте!;
{0}, сделайте выбор!;{0}, вы выбираете;{0}, вы выбираете следующий вопрос`,
		replic_ShowmanGreeting: 'Здравствуйте, здравствуйте, добрый день, это «SIGame»!',
		replic_UnsupportedQuestion: 'Этот вопрос должен разыгрываться вручную. Игра продолжится спустя небольшое время',
		requestedAppellation: '{0} запросил(а) апелляцию',
		resetToDefaults: 'По умолчанию',
		resetToDefaultsHint: 'Сбрасывает все настройки в их исходное состояние',
		removeContentItem: 'Удалить элемент контента',
		removeOption: 'Удалить вариант',
		removeScreen: 'Удалить экран',
		restriction: 'Ограничение',
		restrictionIssue: 'Нарушение ограничения (по возрасту, региону и т.п.)',
		results: 'Результаты',
		resume: 'Продолжить',
		reviews: 'Отзывы',
		rightAnswer: 'Правильный ответ',
		rightAnswers: 'Правильные ответы',
		role: 'Роль',
		room: 'Комната',
		round: 'Раунд',
		roundAuthors: 'Авторы раунда',
		roundComments: 'Комментарии раунда',
		roundEndedEmpty: 'Раунд завершён, так как не осталось вопросов',
		roundEndedManual: 'Раунд завершён вручную',
		roundEndedTimeout: 'Раунд завершён по таймауту',
		roundCount: 'Число раундов',
		rounds: 'Раунды',
		roundsAndThemes: 'Раунды и темы',
		roundSources: 'Источники раунда',
		roundThemes: 'Темы раунда',
		roundTypeTable: 'Таблица',
		rules: 'Правила',
		rulesClassic: 'Классический',
		rulesRemoveThemes: 'Игроки по очереди убирают темы. Играется вопрос из оставшейся темы',
		rulesSequential: 'Вопросы играются по очереди',
		score: 'Счёт',
		scoreEarned: 'Заработано очков',
		scoreFactor: 'Мультипликатор стоимости',
		scoreLost: 'Потеряно очков',
		screenDuration: 'Длительность (с)',
		search: 'Поиск',
		searchGames: 'Поиск комнат',
		searchHint: 'Начните поиск, чтобы увидеть список комнат',
		sec: 'с',
		second: 'сек',
		seconds2: 'сек',
		seconds5: 'сек',
		select: 'Выбрать…',
		selectAnswerer: 'Выберите игрока, которому вы отдаёте вопрос',
		selectAvatar: 'Выбрать аватар',
		selectFirstPlayer: 'Выберите начинающего раунд',
		selectionMode: 'Режим передачи',
		selectStaker: 'Выберите ставящего',
		selectThemeDeleter: 'Выберите убирающего тему',
		send: 'Отправить',
		sendingPackage: 'Отправка пакета на сервер…',
		savePackage: 'Сохранить пакет',
		server: 'Сервер',
		serverLicense: 'Лицензия сервера',
		setAnswererSelectAny: 'Кому угодно',
		setAnswererSelectExceptCurrent: 'Всем кроме себя',
		setChooser: '{0} передал(а) ход {1}',
		setJoinMode: 'задал(а) режим входа в комнату',
		settings: 'Настройки',
		set: 'Задать',
		setHost: 'Сделать хостом',
		sex: 'Пол',
		showAnswers: 'Показать ответы',
		showChat: 'Показать чат',
		showman: 'Ведущий',
		showVideoAvatars: 'Показывать видео аватары',
		singlePlay: 'Одиночная игра',
		size: 'Размер',
		sort: 'Сортировка',
		sound: 'Звук',
		soundApp: 'Звук приложения',
		sounds: 'Звуки',
		soundsUpload: 'Загрузить пользовательский звук',
		soundsReset: 'Сбросить к стандартному',
		soundAnswerWrong: 'Неправильный ответ',
		soundApplauseBig: 'Большие аплодисменты',
		soundApplauseFinal: 'Финальные аплодисменты',
		soundApplauseSmall: 'Малые аплодисменты',
		soundFinalDelete: 'Удаление темы финального раунда',
		soundFinalThink: 'Обдумывание в финальном раунде',
		soundMainMenu: 'Главное меню',
		soundQuestionAll: 'Вопрос для всех',
		soundQuestionForYourself: 'Вопрос для себя',
		soundQuestionNoAnswers: 'Нет ответа',
		soundQuestionSecret: 'Вопрос с секретом',
		soundQuestionStake: 'Вопрос со ставкой',
		soundQuestionStakeAll: 'Вопрос со ставкой для всех',
		soundRoomEntry: 'Вход в комнату',
		soundRoundBegin: 'Раунд',
		soundRoundThemes: 'Темы раунда',
		soundRoundTimeout: 'Таймаут раунда',
		soundVolume: 'Громкость звука',
		sources: 'Источники',
		sourcesInfo: 'Страница исходного кода игры.',
		sport: 'Упрощённая',
		sportPlural: 'Упрощённые',
		started: 'Начата',
		startGame: 'Создать',
		startGameHint: 'Начать игру, не дожидаясь готовности участников',
		status: 'Статус',
		steamWorkshop: 'Мастерская Steam',
		supportInfo: 'Страница технической поддержки.',
		symbolsPerSecond: 'символов в секунду',
		syntaxError: 'Синтаксическая ошибка',
		table: 'Табло',
		tableHint: 'Для ответа на вопрос нажимайте на кнопку после загорания рамки на экране. Игра начнётся, когда все участники будут готовы',
		tableLogoAuthor: 'Автор игры - Владимир Хиль',
		tags: 'Теги',
		text: 'Текст',
		textColor: 'Цвет текста',
		theGameWillStartIn: 'Игра начнётся через',
		thePlayerThinksThatHisHerAnswer: 'Игрок считает, что его ответ',
		theme: 'Тема',
		themeAuthors: 'Авторы темы',
		themeCount: 'Число тем (в раунде)',
		themeCountFinal: 'Число тем (в финале)',
		includeFinalRound: 'Включить финальный раунд',
		authorName: 'Имя автора',
		themeList: 'Список тем',
		themeSources: 'Источники темы',
		time: 'Время',
		timeForBlockingButton: 'Блокировка кнопки при фальстарте',
		timeForChoosingFinalTheme: 'Выбор темы (удаление)',
		timeForChoosingQuestion: 'Выбор вопроса',
		timeForFinalThinking: 'Ответ на вопрос для всех',
		timeForGivingACat: 'Выбор другого игрока (передача вопроса)',
		timeForMakingStake: 'Ставка',
		timeForPrintingAnswer: 'Ответ после нажатия на кнопку',
		timeForRightAnswer: 'Вывод правильного ответа',
		timeForShowmanDecisions: 'Решения ведущего',
		timeForThinkingOnQuestion: 'Нажатие кнопки (уменьшение рамки для ответа)',
		timeForThinkingOnSpecial: 'Ответ на спецвопрос',
		timeOfRound: 'Раунд',
		to: 'до',
		tooManyGamesByIp: 'Слишком много игр на одном адресе!',
		tooManyRequests: 'Слишком много запросов. Пожалуйста, обратитесь позже',
		topPackages: 'Топ пакеты (неделя)',
		total: 'Всего:',
		trends: 'Тренды',
		turnTaking: 'Игра по очереди',
		tv: 'Классическая',
		tvPlural: 'Классические',
		type: 'Тип',
		unban: 'Снять бан',
		unknownError: 'Неизвестная ошибка',
		unsupportedBrowser: 'Ваш браузер не поддерживается. Пожалуйста, обновите или замените его',
		unsupportedMediaType: 'Неподдерживаемый тип медиа',
		uploadingImageError: 'Ошибка отправки аватара',
		uploadingPackageError: 'Ошибка отправки пакета',
		useApellations: 'Апелляции ответов',
		useApellationsHint: 'Кнопки "Я прав" и "Я против"',
		useProxy: 'Использовать прокси-соединение',
		useProxyHint: 'При наличии',
		useProxyOnErrors: 'Если не удаётся подключиться к игре напрямую, попробуйте включить или отключить прокси в настройках',
		usedComponents: 'Используемые в игре компоненты и их лицензии:',
		userPackages: 'Пользовательские пакеты',
		users: 'Игроки',
		userUnbanned: 'Пользователь {0} был разбанен',
		validateAnswer: 'Верен ли ответ?',
		video: 'Видео',
		videoAvatar: 'Видео аватар',
		viewer: 'Зритель',
		viewers: 'Зрители',
		viewMode: 'Режим просмотра',
		editMode: 'Режим редактирования',
		enableEditMode: 'Включить режим редактирования',
		editModeDisclaimer: 'Режим редактирования является экспериментальным. Используйте на свой риск. Сохраняйте часто.',
		downloadPackageStatistics: 'Загрузить статистику пакета',
		loadingStatistics: 'Загрузка статистики...',
		completedGames: 'Завершенных игр: {0} из {1} ({2}%)',
		answerTries: 'Попытки ответа',
		voiceChat: 'Голосовой чат',
		webCameraUrl: 'Адрес веб-камеры',
		welcomeTitle: 'Выберите действие',
		managedGameEnabled: 'Режим управляемой игры включён {0}',
		managedGameDisabled: 'Режим управляемой игры отключён {0}',
		falseStartEnabled: 'Режим фальстартов включён {0}',
		falseStartDisabled: 'Режим фальстартов отключён {0}',
		readingSpeedChanged: 'Скорость чтения изменена {0} на {1}',
		partialTextEnabled: 'Частичный вывод текста включён {0}',
		partialTextDisabled: 'Частичный вывод текста отключён {0}',
		partialImagesEnabled: 'Частичный вывод изображений включён {0}',
		partialImagesDisabled: 'Частичный вывод изображений отключён {0}',
		partialImageTimeChanged: 'Время вывода частичных изображений изменено {0} на {1}',
		useApellationsEnabled: 'Апелляции включены {0}',
		useApellationsDisabled: 'Апелляции отключены {0}',
		blockingTimeChanged: 'Время блокировки кнопки изменено {0} на {1}',
		displayLabelsEnabled: 'Отображение букв вариантов ответа включено {0}',
		displayLabelsDisabled: 'Отображение букв вариантов ответа отключено {0}',
		withButton: 'С кнопкой',
		withoutPassword: 'Без пароля',
		withStep: 'с шагом',
		writeGameLog: 'Записывать журнал игры',
		wrongAnswer: 'Неправильный ответ',
		wrongAnswers: 'Неправильные ответы',
		wrongGameSettings: 'Неверные настройки игры!',
		yes: 'Да',
		youAreKicked: 'Вас выгнали из игры!',
		yourName: 'Ваше имя',
		custom: 'Произвольный',
		enterAnswer: 'Введите ответ',
		enterAuthorName: 'Введите имя автора',
		enterCustomQuestionType: 'Введите произвольный тип вопроса',
		enterSource: 'Введите источник',
		enterTag: 'Введите тег',
		enterTextContent: 'Введите текст...',
		enterWrongAnswer: 'Введите неправильный ответ'
	},
	sr: {
		about: [
			'SIGame je intelektualna viktorina u kojoj svako može da testira svoje znanje i brzinu reakcije i bori se protiv protivnika.',
			`Pravila igre su veoma jednostavna: sva pitanja u igri su podeljena po temama,
			 i svako pitanje u temi ima svoju cenu.
			 Svaki igrač ima lični rezultat, koji na početku igre iznosi 0.
			 Predstavlja se pitanje, nakon čega se pojavljuje okvir na ekranu koji pokazuje da možete da pritisnete dugme i odgovorite.
			 Ako igrač zna odgovor, može da pritisne crveno dugme. Igrač koji pritisne dugme ranije od drugih
			 (i neće imati lažni početak), daje odgovor. Ako je odgovor tačan, cena pitanja se dodaje na rezultat igrača;
			 u suprotnom - cena se oduzima od rezultata.
			 U potoanjem slučaju, drugi igrači mogu pokušati sreću i pritisnuti dugme da odgovore.`,
			`Postoje i specijalna pitanja u igri.
			U "Pitanju sa ulogom" učesnici se nadmeću za pitanje, a igrač sa najvišim ulogom odgovara.
			U ovom slučaju, "Sve ili ništa" ulog (ulog koji je jednak celom rezultatu igrača) može biti nadmašen samo drugim "Sve ili ništa".`,
			`"Tajno pitanje" mora biti dato drugom igraču.
			Igrač koji ga je primio mora (ako je uključeno u pitanje) da izabere cenu pitanja i odgovori na njega.
			Tema pitanja može se razlikovati od glavne teme u kojoj je pitanje otvoreno.`,
			'"Pitanje za sebe" odgovara igrač koji ga je otvorio.',
			`Igra takođe može imati finalnu rundu u kojoj svaki od igrača postavlja ulog.
			Postavlja se pitanje, daje se vreme za razmišljanje, i svaki od igrača šalje svoj odgovor domaćinu.
			Nakon toga se objavljuje tačan odgovor, i svaki od igrača dobija ili gubi novac prema svom ulogu.`,
			'Pobednik igre je igrač sa najvišim rezultatom nakon poslednjeg pitanja.',
			'Dugme za igru se takođe može aktivirati pomoću imenovanog tastera ili desnog dugmeta miša.'
		],
		aboutAuthor: 'Autor',
		aboutSupport: 'Tehnička podrška',
		aboutTitle: 'O igri',
		acceptLicense: 'Prihvatiti licencu',
		addedNewSlot: '{0} je dodao novi slot igrača',
		addOption: 'Dodati opciju',
		addContentItem: 'Dodati element sadržaja',
		addScreen: 'Dodati ekran',
		addTable: 'Dodati sto',
		all: 'Sve',
		allIn: 'SVE ILI NIŠTA!',
		allowEveryoneToPlayHiddenStakes: 'Igraju svi igrači',
		allowEveryoneToPlayHiddenStakesHint: 'čak i sa 0 ili negativnim rezultatom',
		answer: 'Odgovor',
		answerChecking: 'Provera odgovora',
		answerOptions: 'Opcije odgovora',
		answerType: 'Tip odgovora',
		answerTypeSelect: 'Izbor iz opcija',
		anyonePlay: 'Igra sa slučajnim protivnicima',
		apellateAnswer: 'Žaliti se na odgovor',
		apellation: 'Žalba',
		appellationMark: 'Zatražena žalba',
		apiCallsQuotaExceeded: 'Premašen limit zahteva. Pokušajte kasnije',
		appName: 'SIGame',
		appUser: 'SIGame',
		ascending: 'rastuće',
		attachContentToTable: 'Dodavati komentare teme i tačan odgovor na tablu',
		audio: 'Audio',
		audioLoadError: 'Greška pri učitavanju audija',
		authorInfo: 'Vladimir Hilj',
		authors: 'Autori',
		avatar: 'Avatar',
		avatarLoadError: 'Greška pri slanju avatara',
		backgroundColor: 'Boja pozadine',
		backgroundImage: 'Slika pozadine',
		badPackage: 'Loš paket pitanja!',
		ban: 'Zabraniti',
		bannedNotification: '{0} je izbacio {1} iz igre',
		bannedList: 'Lista zabranjenih',
		blocked: '(Blokiran)',
		bot: 'Bot',
		buttonPressMode: 'Režim pritiska dugmeta',
		buttonPressModeFirstWins: 'Ko je prvi pritisnuo (prema serveru)',
		buttonPressModeFirstWinsClient: 'Ko je prvi pritisnuo (prema klijentu)',
		buttonPressModeRandomWithinInterval: 'Slučajan od ranih pritisnutih',
		by: 'od',
		byGame: 'igrom',
		cancel: 'Otkazati',
		cancelAnswer: 'Otkazati odgovor igrača',
		cannotConnectToServer: 'Nije moguće povezivanje sa serverom',
		changedSlotType: '{0} je promenio tip slota igrača {1} na: {2}',
		changeSums: 'Promeniti sume',
		changeToBot: 'Zameniti botom',
		changeToHuman: 'Zameniti čovekom',
		chat: 'Čat',
		chooserMark: 'Oznaka birača pitanja',
		close: 'Zatvoriti',
		comment: 'Komentar',
		comments: 'Komentari',
		common: 'Zajedničko',
		complain: 'Žaliti se',
		complainHint: 'Pitanje sadrži pravopisnu ili faktičku grešku',
		composer: 'Kompozitor',
		computer: 'Bot',
		computerAccountsMissing: 'Računarski nalozi nisu učitani. Pokušajte da ponovo učitate igru',
		computerPlayers: 'Botovi',
		connected: '{0} se povezao(la)',
		connectionClosed: 'Veza sa serverom je prekinuta!',
		connectionReconnecting: 'Veza je izgubljena, pokušavamo ponovno povezivanje…',
		connectionReconnected: 'Veza je obnovljena!',
		contactUri: 'Kontakt autora',
		content: 'Sadržaj',
		cookiesConfirm: 'Prihvatiti',
		cookiesWarning: 'Ova aplikacija koristi kolačiće. Ostajanjem na ovoj stranici, slažete se sa tim',
		copyrightIssue: 'Kršenje autorskih prava',
		copyText: 'Kopirati tekst u klipbord',
		corruptedPackage: 'Paket pitanja je oštećen!',
		created: 'Kreirano',
		createOwnPackage: 'Kreirati svoj paket',
		createPackage: 'Kreirati paket',
		creatingGame: 'Kreiranje igre…',
		date: 'Datum',
		default: 'Obični',
		defaultFont: '(podrazumevano)',
		defaultShowman: 'Leonardo da Vinči',
		delete: 'Obrisati',
		deleteAvatar: 'Obrisati avatar',
		deletedSlot: '{0} je obrisao slot igrača {1}',
		deleteTable: 'Obrisati sto',
		demoAbout: `SIGame je intelektualna viktorina gde možete testirati svoje znanje i brzinu reakcije protiv protivnika.
		Brzina i znanje su ključ pobede.
		Pitanje se postavlja, nakon čega se na ekranu pojavljuje okvir koji pokazuje da možete pritisnuti dugme i odgovoriti`,
		demoCorrectAnswer: 'Dali ste tačan odgovor! Vaš rezultat je uvećan za cenu pitanja',
		demoFalseStarts: 'Ako igra teče bez lažnih startova, okvir (i mogućnost pritiska dugmeta) će se pojaviti odmah sa pitanjem',
		demoFinished: 'Demo režim je završen. Hvala! Želimo vam uspešnu igru!',
		demoGameRules: 'Odgovarajući na pitanja, zarađujete poene. U igri pobeduje onaj ko naskuplja više poena',
		demoGiveAnswer: 'Sada ukucajte odgovor na pitanje. Napišite: ODGOVOR i pritisnite dugme Pošalji',
		demoOpponents: `Možete igrati sa botovima ili pozvati prijatelje.
		Možete igrati na gotovim pitanjima u igri, koristiti pitanja drugih autora ili napisati svoja`,
		demoOtherContent: `U pitanjima mogu biti slike, audio ili video.
		Mogu se pojaviti pitanja sa opcijama odgovora, gde treba izabrati tačnu opciju`,
		demoOtherQuestions: `U igri mogu biti i druga pitanja, na primer, sa tajnom ili sa ulogom.
		Za svaku vrstu specijalnih pitanja biće objašnjenja tokom igre`,
		demoQuestion: `Ovo je demo pitanje. Pritisnite dugme da odgovorite.
		Ako pritisnete dugme pre nego što se pojavi okvir, to će biti lažni početak i vaše dugme neće raditi neko vreme.
		Ako pritisnete dugme, ali drugi igrač vas pretekne, vaše dugme će takođe biti blokirano.
		Prvi igrač koji pritisne dugme će odgovarati na pitanje`,
		demoWelcome: `Dobrodošli u SIGame!
		Uvek možete izaći iz demo režima pritiskom na dugme "Izaći" u uglu ekrana.
		Za početak demonstracije pritisnite dugme "Spreman" (zelenoj kućici)`,
		demoWrongAnswer: 'Dali ste pogrešan odgovor! Vaš rezultat je smanjen za cenu pitanja',
		descending: 'opadajuće',
		disconnected: '{0} diskonektovan(vna)',
		difficulty: 'Težina',
		disableSound: 'Isključiti zvuk',
		siStorageDisclaimer: `Pažnja! U ovom odeljku se nalaze materijali spoljašnjih autora.
		Autori paketa u biblioteci odgovorni su za sadržaj paketa, njihovu tačnost i usklađenost sa zakonom`,
		displayAnswerOptionsLabels: 'Prikazivati slova opcija odgovora',
		displayAnswerOptionsOneByOne: 'Prikazivati opcije odgovora jednu po jednu',
		displaySources: 'Prikazivati izvore pitanja',
		donate: 'Donirati',
		donateComment: `Donacije nisu obavezne i koriste se isključivo za pokrivanje hostinga i domena.
		Projekat je nekomercijalan i postoji u obrazovne svrhe.
		Sva funkcionalnost igre dostupna je besplatno - donacije ne utiču na tok igre
		i ne koriste se za pristup dodatnim funkcijama igre. Hvala na podršci!`,
		donateServersHosting: 'DONACIJE: razvoj, hosting',
		download: 'Preuzeti',
		downloadCount: 'Broj preuzimanja',
		downloadGameLog: 'Preuzeti dnevnik igre',
		downloadingPackage: 'Učitavanje paketa iz skladišta…',
		drop: 'Odbaciti',
		duplicateUserName: 'Korisnik sa tim imenom je već ušao na server!',
		duration: 'Trajanje',
		editTable: 'Urediti tablu',
		editTables: 'Urediti stolove',
		enableSound: 'Uključiti zvuk',
		enter: 'Ulaz',
		enterPin: 'Unesite PIN kod za ulazak u igru',
		errorBadPackage: 'Loš paket pitanja!',
		errorDuplicateGameName: 'Igra sa tim imenom već postoji!',
		errorHappened: 'Greška',
		errorInternalServerError: 'Nije moguće kreirati igru na serveru zbog greške na serveru!',
		errorObsoleteVersion: 'Vaša verzija igre je zastarela. Ažurirajte igru',
		errorPackageNotFound: 'Nije moguće kreirati igru na serveru jer paket igre nije pronađen!',
		errorServerNotReady: 'Server nije spreman da počne igru',
		errorServerUnderMaintainance: `Održavanje servera u toku! Molimo povežite se nakon nekog vremena.
		Izvinjavam se zbog uzrokovane neprijatnosti.`,
		errorTolerant: 'pravo na grešku',
		errorTooManyGames: 'Premašen maksimalni broj pokretanih igara na serveru! Molimo sačekajte.',
		errorUnknownError: 'Nije moguće kreirati igru iz nepoznatog razloga!',
		exit: 'Izaći',
		exitConfirmation: 'Stvarno izaći?',
		exitError: 'Nije moguće izaći iz igre!',
		exitFromGame: 'Izaći iz igre',
		externalMediaDetected: 'Otkriveno spoljašnje medije',
		externalMediaDescription: 'Ovaj sadržaj se ne učitava automatski',
		externalMediaLoad: 'Učitaj spoljašnje medije',
		failedToCompleteNegotiationWithTheServer: 'Nije moguće završiti pregovore sa serverom',
		failedToFetch: 'Nije moguće poslati zahtev na server. Proverite internet vezu, kontaktirajte internet provajdera ili uzmite u obzir moguća regionalna ograničenja',
		falseStarts: 'Lažni počeci',
		falseStartsHint: 'ne možete pritisnuti dugme pre završetka čitanja pitanja',
		female: 'žena',
		file: 'Fajl sa pitanjima',
		fileIsTooBig: 'Fajl premašuje maksimalnu veličinu!',
		fileNonReadable: 'Ne može se otvoriti fajl. Možda je promenjen. Molimo izaberite ga ponovo',
		filter: 'Filter',
		final: 'Finale',
		floatingControls: 'Automatsko sakrivanje kontrola igre',
		font: 'Font',
		forbiddenNickname: 'Na serveru je zabranjeno korišćenje takvog nadimka!',
		freedSlot: '{0} je oslobodio slot sa {1}',
		freeTable: 'Osloboditi sto',
		friendsPlay: 'Igrati sa prijateljima',
		from: 'od',
		fullScreen: 'Režim punog ekrana',
		game: 'Igra',
		gameAuthor: 'Autor programa',
		gameButton: 'Dugme igre',
		gameButtonKey: 'Taster dugmeta igre',
		gameClosed: 'Igra završena od strane servera zbog neaktivnosti',
		gameCount: 'Ukupno igara',
		gameDuration: 'Ukupno trajanje',
		gameError: 'Greška igre',
		gameFinished: 'Igra završena',
		gameInfo: 'Informacije o igri',
		gameJoin: 'Ulazak u igru',
		gameManageHint: 'Promeniti rundu',
		gameName: 'Naziv',
		gameNameMustBeSpecified: 'Potrebno je zadati naziv igre',
		gameNotFound: 'Igra nije pronađena',
		gameLoading: 'Učitavanje igre u toku…',
		gameOf: 'Igra od',
		gameResults: 'Rezultati igre',
		games: 'Igre',
		gameStarted: 'Igra je počela',
		gameStatistics: 'Statistika igre',
		gamesTitle: 'Pronađite sobu u listi ili kreirajte novu',
		gameThemes: 'Teme igre',
		gameType: 'Tip igre',
		gameTypeClassicTableHint: 'Tabla: pitanja biraju igrači. Osnovni tip pitanja: sa dugmetom',
		gameTypeClassicThemeListHint: 'Lista tema: uklanjaju se teme i igra se poslednja. Osnovni tip pitanja: za sve sa ulogom',
		gameTypeQuizTableHint: 'Tabla: pitanja se igraju po redu. Osnovni tip pitanja: za sve',
		gameTypeQuizThemeListHint: 'Lista tema: pitanja se igraju po redu. Osnovni tip pitanja: za sve',
		gameTypeSimpleTableHint: 'Tabla: pitanja se igraju po redu. Osnovni tip pitanja: sa dugmetom',
		gameTypeSimpleThemeListHint: 'Lista tema: uklanjaju se teme i igra se poslednja. Osnovni tip pitanja: za sve sa ulogom',
		gameTypeShowGameThemes: 'Pre početka igre prikazuju se teme rundova',
		gameTypeTurnTakingTableHint: `Tabla: pitanja biraju igrači. Osnovni tip pitanja: za sebe.
		Nakon svakog pitanja red prelazi na sledeći igrač`,
		gameTypeTurnTakingThemeListHint: 'Lista tema: uklanjaju se teme i igra se poslednja. Osnovni tip pitanja: za sve sa ulogom',
		getPin: 'PIN kod',
		giveTurn: 'Predati red igraču',
		giveTurnHint: 'Izaberite kome da predate red',
		greeting: 'Dobrodošli u SIGame!',
		hideAnswers: 'Sakriti odgovore',
		hideChat: 'Sakriti čat',
		hintShowman: 'Saopštavati voditelju tačne odgovore unapred',
		host: 'Host',
		hostNameChanged: 'Host igre je promenjen od strane {0} na {1}',
		hour: 'č',
		hours2: 'č',
		hours5: 'č',
		howToPlay: 'Kako igrati',
		html: 'HTML',
		human: 'Čovek',
		humanPlayers: 'Ljudi',
		iAmRightFemale: 'U pravu sam!',
		iAmRightMale: 'U pravu sam!',
		iDisagree: 'Ne slažem se!',
		iDisagreeHint: 'Osporiti tuđi odgovor',
		ignoreWrong: 'Oduzimati poene za netačan odgovor',
		images: 'Slike',
		imageTime: 'Prikaz slike',
		info: 'Info',
		inputAnswer: 'Napišite odgovor',
		inputNumber: 'Unesite broj',
		invalidNameEmpty: 'Ime ne može biti prazno ili sadržavati samo razmake',
		invalidNameCharacters: 'Ime sadrži nedozvoljene karaktere. Dozvoljeni su samo slova, brojevi, razmaci, crtice, podvlake, tačke i @ simbol',
		invalidNameLength: 'Ime mora imati između 1 i 30 karaktera',
		invalidValueRange: 'Vrednost mora biti između {0} i {1}',
		inviteLink: 'Link za ulazak',
		inviteLinkCopied: 'Link je kopiran',
		isRightValidateIt: 'tačan. Donesite odluku: da li začesti odgovor?',
		joinAsPlayer: 'Igrač',
		joinAsPlayerHint: 'Ući kao igrač',
		joinAsShowman: 'Voditelj',
		joinAsShowmanHint: 'Ući kao voditelj',
		joinAsViewer: 'Gledalac',
		joinAsViewerHint: 'Ući kao gledalac',
		joinByPin: 'Ulazak po PIN kodu',
		joinError: 'Nije moguće povezati se sa igrom',
		joiningGame: 'Povezivanje sa igrom…',
		joinLobby: 'Igra onlajn',
		joinMode: 'Režim ulaska',
		joinModeAnyRole: 'Sa bilo kojom ulogom',
		joinModeForbidden: 'Ulazak zabranjen',
		joinModeViewer: 'Samo kao gledalac',
		keyRight: 'Strelica desno',
		keys: 'Tasteri',
		keySpace: 'Razmak',
		kick: 'Izbaciti',
		language: 'Jezik',
		languageDefault: '(podrazumevano)',
		languageEn: 'English',
		languageRu: 'Русский',
		languageSr: 'Srpski',
		latestGames: 'Poslednje igre',
		lawIssue: 'Kršenje zakona',
		library: 'Biblioteka',
		librarySearchAll: '(sve)',
		librarySearchLessOrEqual: 'manje ili jednako',
		librarySearchMoreOrEqual: 'veće ili jednako',
		librarySearchNotSet: '(nije zadato)',
		librarySelect: 'Izabrati',
		libraryTitle: 'Biblioteka pitanja',
		license: 'Licenca',
		licenseInfo: 'Licenca: dozvoljava se bilo koje korišćenje igre uz uslov navođenja autorstva.',
		loading: 'Učitavanje',
		logo: 'Logotip',
		mainMenuSound: 'Melodija glavnog menija',
		makeAnswer: 'Odgovoriti',
		male: 'muškarac',
		managed: 'Upravljana igra',
		managedHint: 'Igra se nastavlja samo pritiskom na dugme "Dalje"',
		media: 'Mediji',
		mediaLoadedMark: 'Multimedija učitana',
		mediaPreloadProgress: 'Učitavanje medija sadržaja',
		members: 'Učesnici',
		menu: 'Meni',
		message: 'Poruka',
		methodNotAllowed: 'Nepravilan način operacije',
		minMaxInRound: 'Minimum ili maksimum u rundi',
		minute: 'min',
		minutes2: 'min',
		minutes5: 'min',
		myRole: 'Moja uloga',
		name: 'Ime',
		new: 'Nove',
		newGame: 'Nova igra',
		news: 'Vesti',
		next: 'Dalje',
		no: 'Ne',
		nofalsestart: 'bez lažnih početaka',
		nominal: 'Nominal',
		noPackages: 'Paketi nisu pronađeni',
		noPackagesSteam: 'Paketi nisu pronađeni. Idite u Steam Radionicu i pretplatite se na pakete koje želite da koristite u igri',
		notReadyFemale: 'Nisam spremna za igru',
		notReadyMale: 'Nisam spreman za igru',
		noRisk: 'bez rizika',
		noRiskQuestion: 'Pitanje bez rizika',
		answerDeviation: 'Odstupanje odgovora',
		notSet: 'Nije zadato',
		noWarranty: `Igra se distribuira besplatno. Autor ne garantuje pravilno funkcionisanje igre u proizvolјnim uslovima
		i nije odgovoran za bilo koje posledice od korišćenja igre.`,
		number: 'Broj',
		ofGames: 'igara',
		openFile: 'Otvoriti fajl',
		openLibrary: 'Ići u biblioteku',
		oral: 'usmena',
		oralAnswerHint: 'Odgovarajte!',
		oralGame: 'Usmena igra',
		pointAnswerHint: 'Izaberite tačku na slici',
		oralGameDisabled: 'Usmena igra isključena od strane {0}',
		oralGameEnabled: 'Usmena igra uključena od strane {0}',
		oralGameHint: 'Ako je voditelj čovek. Dobro podešavanje za strimove. Igračima je dozvoljeno da biraju i odgovaraju glasom',
		oralPlayersActions: 'Dozvoliti igračima da prave izbor u usmenoj igri',
		orByFilling: 'ili popunjavanjem',
		package: 'Paket',
		other: 'Ostalo',
		packageIsTooBig: 'Paket premašuje maksimalnu veličinu!',
		packages: 'Paketi',
		packageAuthor: 'Autor',
		packageAuthors: 'Autori paketa',
		packageComments: 'Komentari paketa',
		packageDate: 'Datum kreiranja paketa',
		packageDifficulty: 'Težina',
		packageFileWarning: `Otpremanjem paketa na server, potvrđujete da ste autor paketa ili imate prava na njegovo otpremanje.
Autori paketa odgovorni su za sadržaj paketa. Paket će biti automatski obrisan sa servera nakon završetka igre`,
		packageQualityMark: 'Znak kvaliteta',
		packagePublishedDate: 'Datum objavljivanja',
		packagePublisher: 'Izdavač',
		packageRestriction: 'Ograničenje',
		packageSources: 'Izvori paketa',
		packageSubject: 'Tematika',
		page: 'Stranica',
		partialImages: 'Delimični prikaz slika',
		partialImagesHint: 'Pri igri bez lažnih početaka slike se prikazuju delimično',
		partialImageTime: 'Prikaz delimičnih slika',
		partialText: 'Delimični prikaz teksta',
		partialTextHint: 'Pri igri bez lažnih početaka tekst se prikazuje delimično',
		pass: 'Pas',
		password: 'Lozinka',
		passwordRequired: 'Potrebna je lozinka za ulazak',
		pause: 'Pauza',
		penaltyNone: 'Nema kazne (bez rizika)',
		penaltySubtractPoints: 'Oduzimati poene',
		pickAnEmoji: 'Izabrati emoji',
		pin: 'PIN kod',
		pinCopied: 'PIN kod kopiran',
		playAllQuestionsInFinalRound: 'Igrati sva pitanja',
		player: 'Igrač',
		players: 'Igrači',
		playerAnswerLabel: 'Odgovor {0}:',
		playersAnswer: 'Odgovor igrača',
		playerScoreChanged: '{0} je promenio rezultat igrača {1} sa {2} na {3}',
		playWithBots: 'Igrati sa botovima',
		playWithFriends: 'Igrati sa prijateljima',
		position: '#',
		preloadRoundContent: 'Unapred učitati medija sadržaj svim učesnicima na početku runde',
		presents: 'Pokloni',
		presentsPlural: 'Pokloni',
		price: 'Cena',
		profile: 'Profil',
		publisher: 'Izdavač',
		question: 'Pitanje',
		questionAuthors: 'Autori pitanja',
		questionComments: 'Komentari pitanja',
		questionComplain: 'Žalba na pitanje',
		questionCount: 'Broj pitanja',
		questionCountPerTheme: 'Broj pitanja (po temi)',
		questionEditor: 'Uređivač pitanja',
		questionPackage: 'Paket pitanja',
		questionPenalty: 'Kazna za netačan odgovor',
		questionReadingSpeed: 'Brzina čitanja pitanja',
		questionRemoved: '{0} je uklonio pitanje {1}, {2}',
		questionRestored: '{0} je vratio pitanje {1}, {2}',
		questions: 'Pitanja',
		questionsPlayed: 'Igrana pitanja',
		questionSources: 'Izvori pitanja',
		questionTypeForAll: 'Za sve',
		questionTypeForAllHint: 'Pitanje igraju svi igrači',
		questionTypeForAllWithStake: 'Za sve sa ulogom',
		questionTypeForAllWithStakeHint: 'Svako postavlja ulog i igra na njega',
		questionTypeForYourself: 'Za sebe',
		questionTypeForYourselfHint: 'Pitanje igra trenutni igrač',
		questionTypeSecret: 'Sa tajnom',
		questionTypeSecretHint: 'Pitanje se daje igraču i on mora da odgovori',
		questionTypeSecretNoQuestion: 'Sa tajnom bez pitanja',
		questionTypeSecretPublicPrice: 'Sa tajnom i objavljenom cenom',
		questionTypeSimple: 'Sa dugmetom',
		questionTypeSimpleHint: 'Na pitanje odgovara igrač koji pritisne dugme',
		questionTypeStake: 'Sa ulogom',
		questionTypeStakeHint: 'Na pitanje odgovara igrač koji napravi najveći ulog. Sve ili ništa može se nadmašiti samo sa sve ili ništa',
		randomThemes: 'Slučajan skup tema',
		rateGame: 'Oceniti igru',
		reviewPackage: 'Oceniti paket',
		reactions: 'Reakcije',
		readyFemale: 'Spremna sam za igru',
		readyMale: 'Spreman sam za igru',
		reloadPage: 'Osvežiti stranicu',
		replacedSlot: '{0} je zamenio {1} sa {2}',
		replaceWith: 'Zameniti sa',
		replic_Answer: '{0}, kakav je vaš odgovor?;{0}, vaš odgovor?;{0}?;{0}, odgovarajte!;{0}, slušam vas;{0}, molim, odgovorite',
		replic_MakeStake: '{0}, koliki je vaš ulog?;{0}, napravite ulog',
		replic_RoundSkippedNoPlayers: 'Nemamo igrače koji mogu igrati u sledećoj rundi. Zato je preskačemo',
		replic_SelectAnswerOption: '{0}, izaberite opciju odgovora na tabli',
		replic_SelectPlayer: '{0}, kome ćete dati pitanje?',
		replic_SelectQuestion: '{0}, molim izaberite pitanje!;{0}, napravite izbor!;{0}, vaš je izbor;{0}, birate sledeće pitanje',
		replic_ShowmanGreeting: 'Zdravo, zdravo, dobar dan, ovo je „SIGame"!',
		replic_UnsupportedQuestion: 'Ovo pitanje treba da se igra ručno. Igra će se nastaviti nakon kratke pauze',
		requestedAppellation: 'Zatražena je žalba na odgovor igrača {0}',
		resetToDefaults: 'Podrazumevano',
		resetToDefaultsHint: 'Vraća sva podešavanja u njihovo početno stanje',
		removeContentItem: 'Ukloniti element sadržaja',
		removeOption: 'Ukloniti opciju',
		removeScreen: 'Ukloniti ekran',
		restriction: 'Ograničenje',
		restrictionIssue: 'Kršenje ograničenja (po godinama, regionu itd.)',
		results: 'Rezultati',
		resume: 'Nastaviti',
		reviews: 'Recenzije',
		rightAnswer: 'Tačan odgovor',
		rightAnswers: 'Tačni odgovori',
		role: 'Uloga',
		room: 'Soba',
		round: 'Runda',
		roundAuthors: 'Autori runde',
		roundComments: 'Komentari runde',
		roundEndedEmpty: 'Runda je završena jer nema više pitanja',
		roundEndedManual: 'Runda je završena ručno',
		roundEndedTimeout: 'Runda je završena zbog isteka vremena',
		roundCount: 'Broj rundi',
		rounds: 'Runde',
		roundsAndThemes: 'Runde i teme',
		roundSources: 'Izvori runde',
		roundThemes: 'Teme runde',
		roundTypeTable: 'Tabla',
		rules: 'Pravila',
		rulesClassic: 'Klasična',
		rulesRemoveThemes: 'Igrači redom uklanjaju teme. Igra se pitanje iz poslednje teme',
		rulesSequential: 'Pitanja se igraju redom',
		score: 'Rezultat',
		scoreEarned: 'Zarađeno poena',
		scoreFactor: 'Multiplikator cene',
		scoreLost: 'Izgubljeno poena',
		screenDuration: 'Trajanje (s)',
		search: 'Pretraga',
		searchGames: 'Pretraga soba',
		searchHint: 'Započnite pretragu da vidite listu soba',
		sec: 's',
		second: 'sek',
		seconds2: 'sek',
		seconds5: 'sek',
		select: 'Izabrati…',
		selectAnswerer: 'Izaberite igrača kome dajete pitanje',
		selectAvatar: 'Izabrati avatar',
		selectFirstPlayer: 'Izaberite ko počinje rundu',
		selectionMode: 'Režim predaje',
		selectStaker: 'Izaberite ko postavlja ulog',
		selectThemeDeleter: 'Izaberite ko uklanja temu',
		send: 'Poslati',
		sendingPackage: 'Slanje paketa na server…',
		savePackage: 'Sačuvati paket',
		server: 'Server',
		serverLicense: 'Licenca servera',
		setAnswererSelectAny: 'Bilo kome',
		setAnswererSelectExceptCurrent: 'Svima osim sebe',
		setChooser: '{0} je izabrao birača pitanja: {1}',
		setJoinMode: 'postavio/la režim ulaska u sobu',
		settings: 'Podešavanja',
		set: 'Postaviti',
		setHost: 'Postaviti kao hosta',
		sex: 'Pol',
		showAnswers: 'Pokazati odgovore',
		showChat: 'Pokazati čat',
		showman: 'Voditelj',
		showVideoAvatars: 'Prikazivati video avatare',
		singlePlay: 'Jedinstvena igra',
		size: 'Veličina',
		sort: 'Sortiranje',
		sound: 'Zvuk',
		soundApp: 'Zvuk aplikacije',
		sounds: 'Zvukovi',
		soundsUpload: 'Otpremi prilagođeni zvuk',
		soundsReset: 'Resetuj na standardni',
		soundAnswerWrong: 'Pogrešan odgovor',
		soundApplauseBig: 'Veliki aplauz',
		soundApplauseFinal: 'Finalni aplauz',
		soundApplauseSmall: 'Mali aplauz',
		soundFinalDelete: 'Uklanjanje teme finalne runde',
		soundFinalThink: 'Razmišljanje u finalnoj rundi',
		soundMainMenu: 'Glavni meni',
		soundQuestionAll: 'Pitanje za sve',
		soundQuestionForYourself: 'Pitanje za sebe',
		soundQuestionNoAnswers: 'Nema odgovora',
		soundQuestionSecret: 'Pitanje sa sekretom',
		soundQuestionStake: 'Pitanje sa ulogom',
		soundQuestionStakeAll: 'Pitanje sa ulogom za sve',
		soundRoomEntry: 'Ulazak u sobu',
		soundRoundBegin: 'Runda',
		soundRoundThemes: 'Teme runde',
		soundRoundTimeout: 'Taјmaut runde',
		soundVolume: 'Jačina zvuka',
		sources: 'Izvori',
		sourcesInfo: 'Stranica izvornog koda igre.',
		sport: 'Pojednostavljena',
		sportPlural: 'Pojednostavljene',
		started: 'Počela',
		startGame: 'Kreirati',
		startGameHint: 'Početi igru bez čekanja spremnosti učesnika',
		status: 'Status',
		steamWorkshop: 'Steam Radionica',
		supportInfo: 'Stranica tehničke podrške.',
		symbolsPerSecond: 'simbola u sekundi',
		syntaxError: 'Sintaksna greška',
		table: 'Tabla',
		tableHint: 'Za odgovor na pitanje pritisnite dugme nakon što se upali okvir na ekranu. Igra će početi kada svi učesnici budu spremni',
		tableLogoAuthor: 'Autor igre - Vladimir Hilj',
		tags: 'Oznake',
		text: 'Tekst',
		textColor: 'Boja teksta',
		theGameWillStartIn: 'Igra će početi za',
		thePlayerThinksThatHisHerAnswer: 'Igrač smatra da je njegov odgovor',
		theme: 'Tema',
		themeAuthors: 'Autori teme',
		themeCount: 'Broj tema (po rundi)',
		themeCountFinal: 'Broj tema (u finalu)',
		includeFinalRound: 'Uključi finalnu rundu',
		authorName: 'Ime autora',
		themeList: 'Lista tema',
		themeSources: 'Izvori teme',
		time: 'Vreme',
		timeForBlockingButton: 'Blokiranje dugmeta pri lažnom početku',
		timeForChoosingFinalTheme: 'Izbor teme (uklanjanje)',
		timeForChoosingQuestion: 'Izbor pitanja',
		timeForFinalThinking: 'Odgovor na pitanje za sve',
		timeForGivingACat: 'Izbor drugog igrača (predaja pitanja)',
		timeForMakingStake: 'Ulog',
		timeForPrintingAnswer: 'Odgovor nakon pritiska na dugme',
		timeForRightAnswer: 'Prikaz tačnog odgovora',
		timeForShowmanDecisions: 'Odluke voditelja',
		timeForThinkingOnQuestion: 'Pritisak dugmeta (smanjivanje okvira za odgovor)',
		timeForThinkingOnSpecial: 'Odgovor na specijalno pitanje',
		timeOfRound: 'Runda',
		to: 'do',
		tooManyGamesByIp: 'Previše igara na jednoj adresi!',
		tooManyRequests: 'Previše zahteva. Molimo obratite se kasnije',
		topPackages: 'Top paketi (nedelja)',
		total: 'Ukupno:',
		trends: 'Trendovi',
		quiz: 'Kviz',
		turnTaking: 'Igra po redu',
		tv: 'Klasična',
		tvPlural: 'Klasične',
		type: 'Tip',
		unban: 'Ukloniti zabranu',
		unknownError: 'Nepoznata greška',
		unsupportedBrowser: 'Vaš pregledač nije podržan. Molimo ažurirajte ili zamenite ga',
		unsupportedMediaType: 'Nepodržan tip medija',
		uploadingImageError: 'Greška pri slanju avatara',
		uploadingPackageError: 'Greška pri slanju paketa',
		useApellations: 'Žalbe odgovora',
		useApellationsHint: 'Dugmad "U pravu sam" i "Ne slažem se"',
		useProxy: 'Koristi proxy vezu',
		useProxyHint: 'Kada je dostupan',
		useProxyOnErrors: 'Ako ne možete direktno da se povežete sa igrom, pokušajte da omogućite ili onemogućite proksi u podešavanjima',
		usedComponents: 'Komponente korišćene u igri i njihove licence:',
		userPackages: 'Korisnički paketi',
		users: 'Igrači',
		userUnbanned: 'Korisnik {0} je razbanovan',
		validateAnswer: 'Da li je tačan odgovor?',
		video: 'Video',
		videoAvatar: 'Video avatar',
		viewer: 'Gledalac',
		viewers: 'Gledaoci',
		viewMode: 'Režim prikaza',
		editMode: 'Režim uređivanja',
		enableEditMode: 'Uključi režim uređivanja',
		editModeDisclaimer: 'Režim uređivanja je eksperimentalan. Koristite na sopstvenu odgovornost. Čuvajte često.',
		downloadPackageStatistics: 'Preuzmi statistiku paketa',
		loadingStatistics: 'Učitavanje statistike...',
		completedGames: 'Završenih igara: {0} od {1} ({2}%)',
		answerTries: 'Pokušaji odgovora',
		voiceChat: 'Glasovni čat',
		webCameraUrl: 'Adresa veb-kamere',
		welcomeTitle: 'Izaberite akciju',
		managedGameEnabled: 'Režim upravljane igre uključen od strane {0}',
		managedGameDisabled: 'Režim upravljane igre isključen od strane {0}',
		falseStartEnabled: 'Režim lažnih početaka uključen od strane {0}',
		falseStartDisabled: 'Režim lažnih početaka isključen od strane {0}',
		readingSpeedChanged: 'Brzina čitanja promenjena od strane {0} na {1}',
		partialTextEnabled: 'Delimični prikaz teksta uključen od strane {0}',
		partialTextDisabled: 'Delimični prikaz teksta isključen od strane {0}',
		partialImagesEnabled: 'Delimični prikaz slika uključen od strane {0}',
		partialImagesDisabled: 'Delimični prikaz slika isključen od strane {0}',
		partialImageTimeChanged: 'Vreme prikaza delimičnih slika promenjeno od strane {0} na {1}',
		useApellationsEnabled: 'Žalbe uključene od strane {0}',
		useApellationsDisabled: 'Žalbe isključene od strane {0}',
		blockingTimeChanged: 'Vreme blokiranja dugmeta promenjeno od strane {0} na {1}',
		displayLabelsEnabled: 'Prikaz slova opcija odgovora uključen od strane {0}',
		displayLabelsDisabled: 'Prikaz slova opcija odgovora isključen od strane {0}',
		withButton: 'Sa dugmetom',
		withoutPassword: 'Bez lozinke',
		withStep: 'sa korakom',
		writeGameLog: 'Beležiti dnevnik igre',
	wrongAnswer: 'Netačan odgovor',
	wrongAnswers: 'Netačni odgovori',
	wrongGameSettings: 'Neispravne postavke igre!',
	yes: 'Da',
	youAreKicked: 'Izbačeni ste iz igre!',
	yourName: 'Vaše ime',
	custom: 'Prilagođeno',
	enterAnswer: 'Unesite odgovor',
	enterAuthorName: 'Unesite ime autora',
	enterCustomQuestionType: 'Unesite prilagođeni tip pitanja',
	enterSource: 'Unesite izvor',
	enterTag: 'Unesite oznaku',
	enterTextContent: 'Unesite tekst...',
	enterWrongAnswer: 'Unesite netačan odgovor'
}
});export default localization;
